import { describe, expect, test } from "bun:test";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import * as ts from "typescript";

import { FLOWS, OFF_THE_PATH, pathsOnTheDemoPath } from "../../e2e/demo-path";
import { ROUTES } from "../../e2e/routes";
import { MODULES } from "./modules";

/**
 * The demo path, held against the product.
 *
 * `e2e/demo-path.ts` is the list the Definition of Done scopes itself with, and
 * a list that can drift is worth very little: the whole value of "any screen
 * not on the demo path is out of scope" is that somebody can look the answer
 * up. So the list is checked four ways — every step lands on a route that
 * exists, every step that names a step of a drawn process names one the screen
 * still draws, every door it names is still in the application, and every route
 * in the inventory is either on the path or written down as being off it.
 *
 * The last of those is the one that does the work over time. A screen added
 * without a decision about the demo path fails here, at the moment the person
 * who knows the answer is the one looking at the failure.
 */

const ROOT = join(import.meta.dir, "..", "..");

/** Everything a person wrote under src, which is where a door is called from. */
function applicationSource(): string {
  const parts: string[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      // Generated by Lovable, imported by nothing the app reaches, and excluded
      // from both tsconfig and eslint for that reason. A door that survives only
      // there has left the application.
      if (entry.isDirectory()) {
        if (full.endsWith(join("src", "integrations"))) continue;
        walk(full);
      } else if (entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")) {
        parts.push(readFileSync(full, "utf8"));
      }
    }
  };
  walk(join(ROOT, "src"));
  return parts.join("\n");
}

const SOURCE = applicationSource();

/**
 * The stages a screen draws, by the label on each.
 *
 * `/finance`, `/logistics` and `/inventory` declare theirs as `ModuleDef.flow`,
 * so those are read from the declaration itself. `/procurement` and `/sales`
 * draw theirs in the route file, so those are read from what the route hands
 * `<ProcessFlow flow={…}>`: an object written in place, or a constant declared
 * at the top of the same file and named there.
 *
 * The file is parsed, not searched. This read was once the text between
 * `<ProcessFlow` and `actions={`, which held the stages while they were written
 * in place. When both screens moved theirs into a named constant, that text
 * held `flow={PURCHASE_TO_PAY}` and nothing else, every step on both screens
 * read as missing, and the failure blamed the demo path for a screen the read
 * could no longer see. 7376401 followed the name by searching for
 * `const NAME: FlowSpec = {` and the next `\n};`, which a different annotation,
 * a `satisfies` or a reformat would lose again. So a flow this cannot read
 * fails as that.
 */
const INLINE_FLOWS: Readonly<Record<string, string>> = {
  "/procurement": join("routes", "procurement", "index.tsx"),
  "/sales": join("routes", "sales", "index.tsx"),
};

function inlineStages(file: string): string[] {
  const path = join(ROOT, "src", file);
  const tree = ts.createSourceFile(
    path,
    readFileSync(path, "utf8"),
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TSX,
  );
  const said = (node: ts.Node) => node.getText(tree);

  const named = new Map<string, ts.Expression>();
  for (const statement of tree.statements) {
    if (!ts.isVariableStatement(statement)) continue;
    for (const d of statement.declarationList.declarations) {
      if (ts.isIdentifier(d.name) && d.initializer) named.set(d.name.text, d.initializer);
    }
  }

  const given: ts.Expression[] = [];
  const visit = (node: ts.Node) => {
    if (
      (ts.isJsxSelfClosingElement(node) || ts.isJsxOpeningElement(node)) &&
      said(node.tagName) === "ProcessFlow"
    ) {
      for (const attr of node.attributes.properties) {
        if (!ts.isJsxAttribute(attr) || said(attr.name) !== "flow") continue;
        const value = attr.initializer;
        if (value && ts.isJsxExpression(value) && value.expression) given.push(value.expression);
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(tree);
  expect(given.length, `${file} draws no <ProcessFlow flow={…}>`).toBeGreaterThan(0);

  const property = (of: ts.ObjectLiteralExpression, name: string) =>
    of.properties.find(
      (p): p is ts.PropertyAssignment =>
        ts.isPropertyAssignment(p) &&
        (ts.isIdentifier(p.name) || ts.isStringLiteral(p.name)) &&
        p.name.text === name,
    )?.initializer;

  return given.flatMap((flow) => {
    let spec: ts.Expression | undefined = ts.isIdentifier(flow) ? named.get(flow.text) : flow;
    while (
      spec &&
      (ts.isParenthesizedExpression(spec) ||
        ts.isAsExpression(spec) ||
        ts.isSatisfiesExpression(spec))
    ) {
      spec = spec.expression;
    }
    const cannot = `the demo path's check cannot read the flow ${file} gives <ProcessFlow> (flow={${said(flow)}}): it reads an object written in place or a constant declared at the top of the same file`;
    if (!spec || !ts.isObjectLiteralExpression(spec)) throw new Error(cannot);
    const stages = property(spec, "stages");
    if (!stages || !ts.isArrayLiteralExpression(stages)) throw new Error(cannot);

    const labels = stages.elements.map((stage) => {
      const label = ts.isObjectLiteralExpression(stage) ? property(stage, "label") : undefined;
      if (!label || !ts.isStringLiteralLike(label)) {
        throw new Error(
          `${file} draws a step whose label is not written down: ${said(stage).slice(0, 80)}`,
        );
      }
      return label.text;
    });
    expect(labels.length, `${file} draws a <ProcessFlow> with no steps`).toBeGreaterThan(0);
    return labels;
  });
}

function stagesDrawnOn(path: string): string[] | null {
  const inline = INLINE_FLOWS[path];
  if (inline !== undefined) return inlineStages(inline);
  const module = MODULES.find((m) => m.path === path);
  const stages = module?.flow?.stages;
  return stages ? stages.map((s) => s.label) : null;
}

const everyPath = new Set(ROUTES.map((r) => r.path));

describe("the demo path", () => {
  test("is two flows, each starting at the sign-in screen and ending with the four ties proved", () => {
    expect(FLOWS.map((f) => f.key)).toEqual(["purchase-to-pay", "order-to-cash"]);
    for (const flow of FLOWS) {
      expect(flow.steps.length, `${flow.key} has no steps`).toBeGreaterThan(0);
      expect(flow.steps[0]?.path, `${flow.key} does not start where a person starts`).toBe(
        "/signin",
      );
      expect(
        flow.steps[flow.steps.length - 1]?.path,
        `${flow.key} stops before the ties are proved`,
      ).toBe("/operations/assurance");
    }
  });

  test("names only routes the inventory has", () => {
    for (const flow of FLOWS) {
      for (const step of flow.steps) {
        expect(
          everyPath.has(step.path),
          `${flow.key} walks ${step.path}, which is not a route in e2e/routes.ts`,
        ).toBe(true);
      }
    }
  });

  // Separately from the demo path naming anything there: a screen this reads
  // nothing from is a read that has stopped working, not a screen without steps.
  test("can read the steps of every screen that draws its own", () => {
    for (const [path, file] of Object.entries(INLINE_FLOWS)) {
      expect(inlineStages(file).length, `no step read from ${path}`).toBeGreaterThan(0);
    }
  });

  test("names only steps the screens still draw", () => {
    for (const flow of FLOWS) {
      for (const step of flow.steps) {
        if (step.stage === undefined) continue;
        const drawn = stagesDrawnOn(step.path);
        expect(
          drawn,
          `${flow.key} names the ${step.stage} step, and ${step.path} draws no process`,
        ).not.toBeNull();
        expect(
          drawn ?? [],
          `${flow.key} names a "${step.stage}" step on ${step.path}, which draws no such step`,
        ).toContain(step.stage);
      }
    }
  });

  test("names only doors the application still calls", () => {
    for (const flow of FLOWS) {
      for (const step of flow.steps) {
        for (const door of step.doors) {
          expect(door.startsWith("erp_"), `${door} is not a door`).toBe(true);
          expect(
            SOURCE.includes(`"${door}"`),
            `${flow.key} says ${step.path} calls ${door}, which nothing under src does any more`,
          ).toBe(true);
        }
      }
    }
  });

  test("points its signposts at screens it goes on to use", () => {
    for (const flow of FLOWS) {
      flow.steps.forEach((step, i) => {
        if (step.signpost === undefined) return;
        expect(
          everyPath.has(step.signpost),
          `${flow.key} points at ${step.signpost}, which is not a route`,
        ).toBe(true);
        expect(
          flow.steps.slice(i + 1).some((later) => later.path === step.signpost),
          `${flow.key} points at ${step.signpost} and never goes there`,
        ).toBe(true);
        expect(step.doors, `a signpost does no work, so it calls no door`).toEqual([]);
      });
    }
  });

  test("says what the person does and what it leaves behind, at every step", () => {
    for (const flow of FLOWS) {
      for (const step of flow.steps) {
        expect(
          step.does.length,
          `a step of ${flow.key} on ${step.path} says nothing`,
        ).toBeGreaterThan(0);
        expect(
          step.leaves.length,
          `a step of ${flow.key} on ${step.path} does not say what it leaves`,
        ).toBeGreaterThan(0);
      }
    }
  });
});

describe("what is off the demo path", () => {
  test("accounts for every route, once", () => {
    const on = pathsOnTheDemoPath();
    const off = Object.keys(OFF_THE_PATH);

    for (const path of off) {
      expect(
        everyPath.has(path),
        `${path} is written down as off the path and is not a route`,
      ).toBe(true);
      expect(on, `${path} is both on the path and off it`).not.toContain(path);
    }

    expect(
      [...on, ...off].sort(),
      "a route is neither on the demo path nor written down as off it. A new screen needs a " +
        "step in e2e/demo-path.ts or a line in OFF_THE_PATH saying why the two flows do not " +
        "pass through it — that decision is what the Definition of Done's scoping rule spends.",
    ).toEqual([...everyPath].sort());
  });

  test("gives a reason for each, not a heading", () => {
    for (const [path, reason] of Object.entries(OFF_THE_PATH)) {
      expect(reason.length, `${path} is off the path for no stated reason`).toBeGreaterThan(20);
      expect(reason.endsWith("."), `${path}'s reason is not a sentence`).toBe(true);
    }
  });
});
