/**
 * The invitation email: what it says, where its link goes, and the one
 * request that hands it to Resend.
 *
 * Pure on purpose. Nothing here reads the environment, the database or the
 * request, so every rule below can be proved by a unit test with a fake fetch
 * — and the server function that uses it decides who may invite, not this.
 *
 * The organisation name and the inviter's name are typed by a tenant, so
 * both are treated as hostile: squeezed onto one line for the subject and
 * escaped for the HTML. The message carries no images, no tracking pixel and
 * no rewritten links; the only URL in it is the one the person should open.
 */

/** Where a person lands to accept. The token is the whole of the query. */
export function joinLink(origin: string, token: string): string {
  return `${origin.replace(/\/+$/, "")}/join?token=${encodeURIComponent(token)}`;
}

/**
 * Whether a sign-in link generated by Supabase will still arrive at the
 * invitation.
 *
 * Supabase Auth replaces a redirect it does not allow with the project's Site
 * URL and says so only in the `redirect_to` it hands back. A link that lands
 * on the Site URL has lost the token, so it signs somebody in to nothing; the
 * plain join link is the better thing to send.
 */
export function redirectKeepsInvitation(redirectTo: string | null | undefined, link: string) {
  if (!redirectTo) return false;
  try {
    const got = new URL(redirectTo);
    const want = new URL(link);
    return (
      got.origin === want.origin &&
      got.pathname === want.pathname &&
      got.searchParams.get("token") === want.searchParams.get("token")
    );
  } catch {
    return false;
  }
}

const HTML_ESCAPES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};

export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (c) => HTML_ESCAPES[c] ?? c);
}

/**
 * One line, bounded. Control characters and line breaks become spaces, so a
 * name cannot start a second header line or a second paragraph.
 */
export function oneLine(value: string | null | undefined, max = 120): string {
  const flat = [...(value ?? "")]
    .map((c) => (c.charCodeAt(0) < 32 || c.charCodeAt(0) === 127 ? " " : c))
    .join("")
    .replace(/\s+/g, " ")
    .trim();
  return flat.length > max ? `${flat.slice(0, max - 1).trimEnd()}…` : flat;
}

export type InvitationEmailInput = {
  /** The organisation they are invited into. */
  organisation: string | null | undefined;
  /** Who invited them, as the product shows that person's name. */
  inviter: string | null | undefined;
  /** The name the inviter typed for them. */
  inviteeName: string | null | undefined;
  /** The link to open. Used verbatim; build it with joinLink(). */
  link: string;
  /** How long the invitation stays open. */
  expiresInDays: number;
};

export type InvitationEmail = { subject: string; text: string; html: string };

export function invitationEmail(input: InvitationEmailInput): InvitationEmail {
  const organisation = oneLine(input.organisation) || "an organisation";
  const inviter = oneLine(input.inviter);
  const invitee = oneLine(input.inviteeName);
  const days = Math.max(1, Math.round(input.expiresInDays));
  const lasts = days === 1 ? "1 day" : `${days} days`;

  const subject = oneLine(
    inviter
      ? `${inviter} invited you to ${organisation} on Clove ERP`
      : `You are invited to ${organisation} on Clove ERP`,
    200,
  );
  const greeting = invitee ? `Hello ${invitee},` : "Hello,";
  const invited = inviter
    ? `${inviter} has invited you to join ${organisation} on Clove ERP.`
    : `You have been invited to join ${organisation} on Clove ERP.`;
  const terms =
    `The link works once and the invitation expires in ${lasts}. ` +
    "If you are asked to sign in, use this email address.";
  const unexpected =
    "If you did not expect this invitation, you can ignore this email: " +
    "you are not added to anything unless the link is used.";

  const text = [
    greeting,
    "",
    invited,
    "",
    "Accept the invitation:",
    input.link,
    "",
    terms,
    "",
    unexpected,
    "",
  ].join("\n");

  const p = 'style="margin:0 0 16px;font-size:15px;line-height:1.5;color:#1f2933"';
  const small = 'style="margin:0 0 16px;font-size:13px;line-height:1.5;color:#52606d"';
  const href = escapeHtml(input.link);
  const html =
    `<!doctype html><html lang="en"><body style="margin:0;padding:24px;background:#ffffff;` +
    `font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif">` +
    `<div style="max-width:520px">` +
    `<p ${p}>${escapeHtml(greeting)}</p>` +
    `<p ${p}>${escapeHtml(invited)}</p>` +
    `<p style="margin:0 0 16px"><a href="${href}" style="display:inline-block;padding:10px 18px;` +
    `border-radius:6px;background:#1f2933;color:#ffffff;font-size:15px;font-weight:600;` +
    `text-decoration:none">Accept the invitation</a></p>` +
    `<p ${small}>Or open this link: <a href="${href}" style="color:#1f2933;word-break:break-all">${href}</a></p>` +
    `<p ${small}>${escapeHtml(terms)}</p>` +
    `<p ${small}>${escapeHtml(unexpected)}</p>` +
    `</div></body></html>`;

  return { subject, text, html };
}

export type SendResult = { ok: true; id: string } | { ok: false; reason: string };

export const RESEND_ENDPOINT = "https://api.resend.com/emails";

/**
 * Post one message to Resend and say what happened, without throwing.
 *
 * Shaped on worker/src/core/resend.ts, which owns the queue's sends: text and
 * HTML together, "sent" only when Resend names the message, and a failure
 * that says the status and a bounded slice of what came back — never the
 * request, which is where the key is.
 */
export async function sendWithResend(message: {
  apiKey: string;
  from: string;
  to: string;
  subject: string;
  text: string;
  html: string;
  fetchImpl?: typeof fetch;
}): Promise<SendResult> {
  const post = message.fetchImpl ?? fetch;
  let response: Response;
  try {
    response = await post(RESEND_ENDPOINT, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: `Bearer ${message.apiKey}`,
      },
      body: JSON.stringify({
        from: message.from,
        to: [message.to],
        subject: message.subject,
        text: message.text,
        html: message.html,
      }),
    });
  } catch (error) {
    return {
      ok: false,
      reason: `The email service could not be reached (${oneLine(
        error instanceof Error ? error.message : String(error),
        160,
      )})`,
    };
  }

  const body = await response.text().catch(() => "");
  if (!response.ok) {
    let detail = body;
    try {
      const parsed = JSON.parse(body) as { message?: unknown };
      if (typeof parsed.message === "string") detail = parsed.message;
    } catch {
      /* not JSON; the raw text is the detail */
    }
    const said = oneLine(detail, 200);
    return {
      ok: false,
      reason: `The email service refused the message (status ${response.status})${said ? `: ${said}` : ""}`,
    };
  }

  try {
    const accepted = JSON.parse(body) as { id?: unknown };
    if (typeof accepted.id === "string" && accepted.id !== "") return { ok: true, id: accepted.id };
  } catch {
    /* fall through to the refusal below */
  }
  return { ok: false, reason: "The email service accepted the message without naming it" };
}
