import {
  Accessibility,
  ArrowRightLeft,
  Barcode,
  Bell,
  Boxes,
  Building2,
  CalendarRange,
  ClipboardCheck,
  Cog,
  Coins,
  Compass,
  CreditCard,
  Database,
  Factory,
  FileInput,
  FileSignature,
  GitPullRequestArrow,
  Handshake,
  HeartPulse,
  Home,
  KeyRound,
  Languages,
  LineChart,
  Plug,
  Printer,
  Repeat,
  ScanBarcode,
  ScrollText,
  Send,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  Tags,
  Timer,
  Truck,
  UserRound,
  UserX,
  type LucideIcon,
} from "lucide-react";

import type { TileDef } from "./modules";

/**
 * One icon per screen, chosen so the launchpad and rail can be scanned by
 * shape before the label is read. Paths are the key because they are the only
 * identifier every navigation surface already carries.
 */
const ICONS: Record<string, LucideIcon> = {
  "/": Home,
  "/settings": Settings2,
  "/profile": UserRound,
  "/planning": CalendarRange,
  "/procurement": ShoppingCart,
  "/production": Factory,
  "/inventory": Boxes,
  "/logistics": Truck,
  "/sales": Handshake,
  "/commercial/price-book": Tags,
  "/commercial/quotes": FileSignature,
  "/finance": Coins,
  "/quality": ClipboardCheck,
  "/reporting": LineChart,
  "/master-data": Database,
  "/master-data/imports": FileInput,
  "/governance": GitPullRequestArrow,
  "/operations/jobs": Timer,
  "/operations/integrations": Plug,
  "/operations/assurance": ShieldCheck,
  "/operations/continuity": HeartPulse,
  "/operations/devices": ScanBarcode,
  "/device": Barcode,
  "/reporting/distribution": Send,
  "/notifications": Bell,
  "/operations/cutover": ArrowRightLeft,
  "/operations/output": Printer,
  "/reporting/reproducibility": Repeat,
  "/administration/erasure": UserX,
  "/administration/adoption": Compass,
  "/administration/accessibility": Accessibility,
  "/administration/commercial": CreditCard,
  "/administration/configuration": Cog,
  "/administration/permissions": KeyRound,
  "/administration/terminology": Languages,
  "/administration/audit": ScrollText,
  "/administration/tenant": Building2,
};

export function iconFor(path: string): LucideIcon {
  return ICONS[path] ?? Boxes;
}

/** One line of orientation per section of the launchpad. */
export const GROUP_BLURBS: Record<TileDef["group"], string> = {
  plan: "Decide what should happen and when.",
  source: "Bring materials and services in.",
  make: "Turn inputs into finished goods, and check them.",
  move: "Hold, count and ship what exists.",
  sell: "Quote, order and deliver to customers.",
  settle: "Value it, invoice it, close the period.",
  records: "The master data everything depends on, how it changes, and the reports over it.",
  people: "Who is here, what they may do, who approves what, and the plan you are on.",
  system: "The modules you have switched on, and the words this organisation uses.",
  catalogue: "How your products, warehouse and despatch areas are laid out.",
  money: "Where postings land: accounts, cost centres and analysis dimensions.",
  operate: "What runs on its own, and what this is joined to: tasks, gateways, devices, printing.",
  assure: "Proof of what happened: the audit log, personal data, checks and accessibility.",
};
