/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as HelpRouteImport } from './routes/help'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdministrationAccessibilityRouteImport } from './routes/administration/accessibility'
import { Route as AdministrationAdoptionRouteImport } from './routes/administration/adoption'
import { Route as AdministrationAuditRouteImport } from './routes/administration/audit'
import { Route as AdministrationCommercialRouteImport } from './routes/administration/commercial'
import { Route as AdministrationConfigurationRouteImport } from './routes/administration/configuration'
import { Route as AdministrationErasureRouteImport } from './routes/administration/erasure'
import { Route as AdministrationOnboardingRouteImport } from './routes/administration/onboarding'
import { Route as AdministrationOrganisationRouteImport } from './routes/administration/organisation'
import { Route as AdministrationPacksRouteImport } from './routes/administration/packs'
import { Route as AdministrationPermissionsRouteImport } from './routes/administration/permissions'
import { Route as AdministrationTenantRouteImport } from './routes/administration/tenant'
import { Route as AdministrationTerminologyRouteImport } from './routes/administration/terminology'
import { Route as CommercialPriceBookRouteImport } from './routes/commercial/price-book'
import { Route as CommercialQuotesRouteImport } from './routes/commercial/quotes'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents/$documentId'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as FinanceAccountDeterminationRouteImport } from './routes/finance/account-determination'
import { Route as GovernanceIndexRouteImport } from './routes/governance/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as LogisticsIndexRouteImport } from './routes/logistics/index'
import { Route as LogisticsReleaseAreasRouteImport } from './routes/logistics/release-areas'
import { Route as MasterDataIndexRouteImport } from './routes/master-data/index'
import { Route as MasterDataClassificationRouteImport } from './routes/master-data/classification'
import { Route as MasterDataImportsRouteImport } from './routes/master-data/imports'
import { Route as MasterDataItemSupplyRouteImport } from './routes/master-data/item-supply'
import { Route as OperationsAssuranceRouteImport } from './routes/operations/assurance'
import { Route as OperationsContinuityRouteImport } from './routes/operations/continuity'
import { Route as OperationsCutoverRouteImport } from './routes/operations/cutover'
import { Route as OperationsDevicesRouteImport } from './routes/operations/devices'
import { Route as OperationsIntegrationsRouteImport } from './routes/operations/integrations'
import { Route as OperationsJobsRouteImport } from './routes/operations/jobs'
import { Route as OperationsOutputRouteImport } from './routes/operations/output'
import { Route as PlanningIndexRouteImport } from './routes/planning/index'
import { Route as ProcurementIndexRouteImport } from './routes/procurement/index'
import { Route as ProductionIndexRouteImport } from './routes/production/index'
import { Route as QualityIndexRouteImport } from './routes/quality/index'
import { Route as ReportingIndexRouteImport } from './routes/reporting/index'
import { Route as ReportingDistributionRouteImport } from './routes/reporting/distribution'
import { Route as ReportingReproducibilityRouteImport } from './routes/reporting/reproducibility'
import { Route as SalesIndexRouteImport } from './routes/sales/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationAccessibilityRoute =
  AdministrationAccessibilityRouteImport.update({
    id: '/administration/accessibility',
    path: '/administration/accessibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationAdoptionRoute = AdministrationAdoptionRouteImport.update({
  id: '/administration/adoption',
  path: '/administration/adoption',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationAuditRoute = AdministrationAuditRouteImport.update({
  id: '/administration/audit',
  path: '/administration/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationCommercialRoute =
  AdministrationCommercialRouteImport.update({
    id: '/administration/commercial',
    path: '/administration/commercial',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationConfigurationRoute =
  AdministrationConfigurationRouteImport.update({
    id: '/administration/configuration',
    path: '/administration/configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationErasureRoute = AdministrationErasureRouteImport.update({
  id: '/administration/erasure',
  path: '/administration/erasure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationOnboardingRoute =
  AdministrationOnboardingRouteImport.update({
    id: '/administration/onboarding',
    path: '/administration/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationOrganisationRoute =
  AdministrationOrganisationRouteImport.update({
    id: '/administration/organisation',
    path: '/administration/organisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationPacksRoute = AdministrationPacksRouteImport.update({
  id: '/administration/packs',
  path: '/administration/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationPermissionsRoute =
  AdministrationPermissionsRouteImport.update({
    id: '/administration/permissions',
    path: '/administration/permissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationTenantRoute = AdministrationTenantRouteImport.update({
  id: '/administration/tenant',
  path: '/administration/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationTerminologyRoute =
  AdministrationTerminologyRouteImport.update({
    id: '/administration/terminology',
    path: '/administration/terminology',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommercialPriceBookRoute = CommercialPriceBookRouteImport.update({
  id: '/commercial/price-book',
  path: '/commercial/price-book',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialQuotesRoute = CommercialQuotesRouteImport.update({
  id: '/commercial/quotes',
  path: '/commercial/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAccountDeterminationRoute =
  FinanceAccountDeterminationRouteImport.update({
    id: '/finance/account-determination',
    path: '/finance/account-determination',
    getParentRoute: () => rootRouteImport,
  } as any)
const GovernanceIndexRoute = GovernanceIndexRouteImport.update({
  id: '/governance/',
  path: '/governance/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsIndexRoute = LogisticsIndexRouteImport.update({
  id: '/logistics/',
  path: '/logistics/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsReleaseAreasRoute = LogisticsReleaseAreasRouteImport.update({
  id: '/logistics/release-areas',
  path: '/logistics/release-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataIndexRoute = MasterDataIndexRouteImport.update({
  id: '/master-data/',
  path: '/master-data/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataClassificationRoute =
  MasterDataClassificationRouteImport.update({
    id: '/master-data/classification',
    path: '/master-data/classification',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataImportsRoute = MasterDataImportsRouteImport.update({
  id: '/master-data/imports',
  path: '/master-data/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataItemSupplyRoute = MasterDataItemSupplyRouteImport.update({
  id: '/master-data/item-supply',
  path: '/master-data/item-supply',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsAssuranceRoute = OperationsAssuranceRouteImport.update({
  id: '/operations/assurance',
  path: '/operations/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsContinuityRoute = OperationsContinuityRouteImport.update({
  id: '/operations/continuity',
  path: '/operations/continuity',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsCutoverRoute = OperationsCutoverRouteImport.update({
  id: '/operations/cutover',
  path: '/operations/cutover',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsDevicesRoute = OperationsDevicesRouteImport.update({
  id: '/operations/devices',
  path: '/operations/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIntegrationsRoute = OperationsIntegrationsRouteImport.update({
  id: '/operations/integrations',
  path: '/operations/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsJobsRoute = OperationsJobsRouteImport.update({
  id: '/operations/jobs',
  path: '/operations/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsOutputRoute = OperationsOutputRouteImport.update({
  id: '/operations/output',
  path: '/operations/output',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningIndexRoute = PlanningIndexRouteImport.update({
  id: '/planning/',
  path: '/planning/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementIndexRoute = ProcurementIndexRouteImport.update({
  id: '/procurement/',
  path: '/procurement/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityIndexRoute = QualityIndexRouteImport.update({
  id: '/quality/',
  path: '/quality/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingIndexRoute = ReportingIndexRouteImport.update({
  id: '/reporting/',
  path: '/reporting/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingDistributionRoute = ReportingDistributionRouteImport.update({
  id: '/reporting/distribution',
  path: '/reporting/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingReproducibilityRoute =
  ReportingReproducibilityRouteImport.update({
    id: '/reporting/reproducibility',
    path: '/reporting/reproducibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/platform': typeof PlatformRoute
  '/product': typeof ProductRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/administration/accessibility': typeof AdministrationAccessibilityRoute
  '/administration/adoption': typeof AdministrationAdoptionRoute
  '/administration/audit': typeof AdministrationAuditRoute
  '/administration/commercial': typeof AdministrationCommercialRoute
  '/administration/configuration': typeof AdministrationConfigurationRoute
  '/administration/erasure': typeof AdministrationErasureRoute
  '/administration/onboarding': typeof AdministrationOnboardingRoute
  '/administration/organisation': typeof AdministrationOrganisationRoute
  '/administration/packs': typeof AdministrationPacksRoute
  '/administration/permissions': typeof AdministrationPermissionsRoute
  '/administration/tenant': typeof AdministrationTenantRoute
  '/administration/terminology': typeof AdministrationTerminologyRoute
  '/commercial/price-book': typeof CommercialPriceBookRoute
  '/commercial/quotes': typeof CommercialQuotesRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/finance/account-determination': typeof FinanceAccountDeterminationRoute
  '/logistics/release-areas': typeof LogisticsReleaseAreasRoute
  '/master-data/classification': typeof MasterDataClassificationRoute
  '/master-data/imports': typeof MasterDataImportsRoute
  '/master-data/item-supply': typeof MasterDataItemSupplyRoute
  '/operations/assurance': typeof OperationsAssuranceRoute
  '/operations/continuity': typeof OperationsContinuityRoute
  '/operations/cutover': typeof OperationsCutoverRoute
  '/operations/devices': typeof OperationsDevicesRoute
  '/operations/integrations': typeof OperationsIntegrationsRoute
  '/operations/jobs': typeof OperationsJobsRoute
  '/operations/output': typeof OperationsOutputRoute
  '/reporting/distribution': typeof ReportingDistributionRoute
  '/reporting/reproducibility': typeof ReportingReproducibilityRoute
  '/finance/': typeof FinanceIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/master-data/': typeof MasterDataIndexRoute
  '/planning/': typeof PlanningIndexRoute
  '/procurement/': typeof ProcurementIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/quality/': typeof QualityIndexRoute
  '/reporting/': typeof ReportingIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/platform': typeof PlatformRoute
  '/product': typeof ProductRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/administration/accessibility': typeof AdministrationAccessibilityRoute
  '/administration/adoption': typeof AdministrationAdoptionRoute
  '/administration/audit': typeof AdministrationAuditRoute
  '/administration/commercial': typeof AdministrationCommercialRoute
  '/administration/configuration': typeof AdministrationConfigurationRoute
  '/administration/erasure': typeof AdministrationErasureRoute
  '/administration/onboarding': typeof AdministrationOnboardingRoute
  '/administration/organisation': typeof AdministrationOrganisationRoute
  '/administration/packs': typeof AdministrationPacksRoute
  '/administration/permissions': typeof AdministrationPermissionsRoute
  '/administration/tenant': typeof AdministrationTenantRoute
  '/administration/terminology': typeof AdministrationTerminologyRoute
  '/commercial/price-book': typeof CommercialPriceBookRoute
  '/commercial/quotes': typeof CommercialQuotesRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/finance/account-determination': typeof FinanceAccountDeterminationRoute
  '/logistics/release-areas': typeof LogisticsReleaseAreasRoute
  '/master-data/classification': typeof MasterDataClassificationRoute
  '/master-data/imports': typeof MasterDataImportsRoute
  '/master-data/item-supply': typeof MasterDataItemSupplyRoute
  '/operations/assurance': typeof OperationsAssuranceRoute
  '/operations/continuity': typeof OperationsContinuityRoute
  '/operations/cutover': typeof OperationsCutoverRoute
  '/operations/devices': typeof OperationsDevicesRoute
  '/operations/integrations': typeof OperationsIntegrationsRoute
  '/operations/jobs': typeof OperationsJobsRoute
  '/operations/output': typeof OperationsOutputRoute
  '/reporting/distribution': typeof ReportingDistributionRoute
  '/reporting/reproducibility': typeof ReportingReproducibilityRoute
  '/finance': typeof FinanceIndexRoute
  '/governance': typeof GovernanceIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/logistics': typeof LogisticsIndexRoute
  '/master-data': typeof MasterDataIndexRoute
  '/planning': typeof PlanningIndexRoute
  '/procurement': typeof ProcurementIndexRoute
  '/production': typeof ProductionIndexRoute
  '/quality': typeof QualityIndexRoute
  '/reporting': typeof ReportingIndexRoute
  '/sales': typeof SalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/platform': typeof PlatformRoute
  '/product': typeof ProductRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/administration/accessibility': typeof AdministrationAccessibilityRoute
  '/administration/adoption': typeof AdministrationAdoptionRoute
  '/administration/audit': typeof AdministrationAuditRoute
  '/administration/commercial': typeof AdministrationCommercialRoute
  '/administration/configuration': typeof AdministrationConfigurationRoute
  '/administration/erasure': typeof AdministrationErasureRoute
  '/administration/onboarding': typeof AdministrationOnboardingRoute
  '/administration/organisation': typeof AdministrationOrganisationRoute
  '/administration/packs': typeof AdministrationPacksRoute
  '/administration/permissions': typeof AdministrationPermissionsRoute
  '/administration/tenant': typeof AdministrationTenantRoute
  '/administration/terminology': typeof AdministrationTerminologyRoute
  '/commercial/price-book': typeof CommercialPriceBookRoute
  '/commercial/quotes': typeof CommercialQuotesRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/finance/account-determination': typeof FinanceAccountDeterminationRoute
  '/logistics/release-areas': typeof LogisticsReleaseAreasRoute
  '/master-data/classification': typeof MasterDataClassificationRoute
  '/master-data/imports': typeof MasterDataImportsRoute
  '/master-data/item-supply': typeof MasterDataItemSupplyRoute
  '/operations/assurance': typeof OperationsAssuranceRoute
  '/operations/continuity': typeof OperationsContinuityRoute
  '/operations/cutover': typeof OperationsCutoverRoute
  '/operations/devices': typeof OperationsDevicesRoute
  '/operations/integrations': typeof OperationsIntegrationsRoute
  '/operations/jobs': typeof OperationsJobsRoute
  '/operations/output': typeof OperationsOutputRoute
  '/reporting/distribution': typeof ReportingDistributionRoute
  '/reporting/reproducibility': typeof ReportingReproducibilityRoute
  '/finance/': typeof FinanceIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/master-data/': typeof MasterDataIndexRoute
  '/planning/': typeof PlanningIndexRoute
  '/procurement/': typeof ProcurementIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/quality/': typeof QualityIndexRoute
  '/reporting/': typeof ReportingIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/device'
    | '/help'
    | '/notifications'
    | '/platform'
    | '/product'
    | '/profile'
    | '/settings'
    | '/administration/accessibility'
    | '/administration/adoption'
    | '/administration/audit'
    | '/administration/commercial'
    | '/administration/configuration'
    | '/administration/erasure'
    | '/administration/onboarding'
    | '/administration/organisation'
    | '/administration/packs'
    | '/administration/permissions'
    | '/administration/tenant'
    | '/administration/terminology'
    | '/commercial/price-book'
    | '/commercial/quotes'
    | '/documents/$documentId'
    | '/finance/account-determination'
    | '/logistics/release-areas'
    | '/master-data/classification'
    | '/master-data/imports'
    | '/master-data/item-supply'
    | '/operations/assurance'
    | '/operations/continuity'
    | '/operations/cutover'
    | '/operations/devices'
    | '/operations/integrations'
    | '/operations/jobs'
    | '/operations/output'
    | '/reporting/distribution'
    | '/reporting/reproducibility'
    | '/finance/'
    | '/governance/'
    | '/inventory/'
    | '/logistics/'
    | '/master-data/'
    | '/planning/'
    | '/procurement/'
    | '/production/'
    | '/quality/'
    | '/reporting/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/help'
    | '/notifications'
    | '/platform'
    | '/product'
    | '/profile'
    | '/settings'
    | '/administration/accessibility'
    | '/administration/adoption'
    | '/administration/audit'
    | '/administration/commercial'
    | '/administration/configuration'
    | '/administration/erasure'
    | '/administration/onboarding'
    | '/administration/organisation'
    | '/administration/packs'
    | '/administration/permissions'
    | '/administration/tenant'
    | '/administration/terminology'
    | '/commercial/price-book'
    | '/commercial/quotes'
    | '/documents/$documentId'
    | '/finance/account-determination'
    | '/logistics/release-areas'
    | '/master-data/classification'
    | '/master-data/imports'
    | '/master-data/item-supply'
    | '/operations/assurance'
    | '/operations/continuity'
    | '/operations/cutover'
    | '/operations/devices'
    | '/operations/integrations'
    | '/operations/jobs'
    | '/operations/output'
    | '/reporting/distribution'
    | '/reporting/reproducibility'
    | '/finance'
    | '/governance'
    | '/inventory'
    | '/logistics'
    | '/master-data'
    | '/planning'
    | '/procurement'
    | '/production'
    | '/quality'
    | '/reporting'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/device'
    | '/help'
    | '/notifications'
    | '/platform'
    | '/product'
    | '/profile'
    | '/settings'
    | '/administration/accessibility'
    | '/administration/adoption'
    | '/administration/audit'
    | '/administration/commercial'
    | '/administration/configuration'
    | '/administration/erasure'
    | '/administration/onboarding'
    | '/administration/organisation'
    | '/administration/packs'
    | '/administration/permissions'
    | '/administration/tenant'
    | '/administration/terminology'
    | '/commercial/price-book'
    | '/commercial/quotes'
    | '/documents/$documentId'
    | '/finance/account-determination'
    | '/logistics/release-areas'
    | '/master-data/classification'
    | '/master-data/imports'
    | '/master-data/item-supply'
    | '/operations/assurance'
    | '/operations/continuity'
    | '/operations/cutover'
    | '/operations/devices'
    | '/operations/integrations'
    | '/operations/jobs'
    | '/operations/output'
    | '/reporting/distribution'
    | '/reporting/reproducibility'
    | '/finance/'
    | '/governance/'
    | '/inventory/'
    | '/logistics/'
    | '/master-data/'
    | '/planning/'
    | '/procurement/'
    | '/production/'
    | '/quality/'
    | '/reporting/'
    | '/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeviceRoute: typeof DeviceRoute
  HelpRoute: typeof HelpRoute
  NotificationsRoute: typeof NotificationsRoute
  PlatformRoute: typeof PlatformRoute
  ProductRoute: typeof ProductRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  AdministrationAccessibilityRoute: typeof AdministrationAccessibilityRoute
  AdministrationAdoptionRoute: typeof AdministrationAdoptionRoute
  AdministrationAuditRoute: typeof AdministrationAuditRoute
  AdministrationCommercialRoute: typeof AdministrationCommercialRoute
  AdministrationConfigurationRoute: typeof AdministrationConfigurationRoute
  AdministrationErasureRoute: typeof AdministrationErasureRoute
  AdministrationOnboardingRoute: typeof AdministrationOnboardingRoute
  AdministrationOrganisationRoute: typeof AdministrationOrganisationRoute
  AdministrationPacksRoute: typeof AdministrationPacksRoute
  AdministrationPermissionsRoute: typeof AdministrationPermissionsRoute
  AdministrationTenantRoute: typeof AdministrationTenantRoute
  AdministrationTerminologyRoute: typeof AdministrationTerminologyRoute
  CommercialPriceBookRoute: typeof CommercialPriceBookRoute
  CommercialQuotesRoute: typeof CommercialQuotesRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  FinanceAccountDeterminationRoute: typeof FinanceAccountDeterminationRoute
  LogisticsReleaseAreasRoute: typeof LogisticsReleaseAreasRoute
  MasterDataClassificationRoute: typeof MasterDataClassificationRoute
  MasterDataImportsRoute: typeof MasterDataImportsRoute
  MasterDataItemSupplyRoute: typeof MasterDataItemSupplyRoute
  OperationsAssuranceRoute: typeof OperationsAssuranceRoute
  OperationsContinuityRoute: typeof OperationsContinuityRoute
  OperationsCutoverRoute: typeof OperationsCutoverRoute
  OperationsDevicesRoute: typeof OperationsDevicesRoute
  OperationsIntegrationsRoute: typeof OperationsIntegrationsRoute
  OperationsJobsRoute: typeof OperationsJobsRoute
  OperationsOutputRoute: typeof OperationsOutputRoute
  ReportingDistributionRoute: typeof ReportingDistributionRoute
  ReportingReproducibilityRoute: typeof ReportingReproducibilityRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  GovernanceIndexRoute: typeof GovernanceIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  LogisticsIndexRoute: typeof LogisticsIndexRoute
  MasterDataIndexRoute: typeof MasterDataIndexRoute
  PlanningIndexRoute: typeof PlanningIndexRoute
  ProcurementIndexRoute: typeof ProcurementIndexRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
  QualityIndexRoute: typeof QualityIndexRoute
  ReportingIndexRoute: typeof ReportingIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/accessibility': {
      id: '/administration/accessibility'
      path: '/administration/accessibility'
      fullPath: '/administration/accessibility'
      preLoaderRoute: typeof AdministrationAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/adoption': {
      id: '/administration/adoption'
      path: '/administration/adoption'
      fullPath: '/administration/adoption'
      preLoaderRoute: typeof AdministrationAdoptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/audit': {
      id: '/administration/audit'
      path: '/administration/audit'
      fullPath: '/administration/audit'
      preLoaderRoute: typeof AdministrationAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/commercial': {
      id: '/administration/commercial'
      path: '/administration/commercial'
      fullPath: '/administration/commercial'
      preLoaderRoute: typeof AdministrationCommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/configuration': {
      id: '/administration/configuration'
      path: '/administration/configuration'
      fullPath: '/administration/configuration'
      preLoaderRoute: typeof AdministrationConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/erasure': {
      id: '/administration/erasure'
      path: '/administration/erasure'
      fullPath: '/administration/erasure'
      preLoaderRoute: typeof AdministrationErasureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/onboarding': {
      id: '/administration/onboarding'
      path: '/administration/onboarding'
      fullPath: '/administration/onboarding'
      preLoaderRoute: typeof AdministrationOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/organisation': {
      id: '/administration/organisation'
      path: '/administration/organisation'
      fullPath: '/administration/organisation'
      preLoaderRoute: typeof AdministrationOrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/packs': {
      id: '/administration/packs'
      path: '/administration/packs'
      fullPath: '/administration/packs'
      preLoaderRoute: typeof AdministrationPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/permissions': {
      id: '/administration/permissions'
      path: '/administration/permissions'
      fullPath: '/administration/permissions'
      preLoaderRoute: typeof AdministrationPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/tenant': {
      id: '/administration/tenant'
      path: '/administration/tenant'
      fullPath: '/administration/tenant'
      preLoaderRoute: typeof AdministrationTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/terminology': {
      id: '/administration/terminology'
      path: '/administration/terminology'
      fullPath: '/administration/terminology'
      preLoaderRoute: typeof AdministrationTerminologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial/price-book': {
      id: '/commercial/price-book'
      path: '/commercial/price-book'
      fullPath: '/commercial/price-book'
      preLoaderRoute: typeof CommercialPriceBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial/quotes': {
      id: '/commercial/quotes'
      path: '/commercial/quotes'
      fullPath: '/commercial/quotes'
      preLoaderRoute: typeof CommercialQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/account-determination': {
      id: '/finance/account-determination'
      path: '/finance/account-determination'
      fullPath: '/finance/account-determination'
      preLoaderRoute: typeof FinanceAccountDeterminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/': {
      id: '/governance/'
      path: '/governance'
      fullPath: '/governance/'
      preLoaderRoute: typeof GovernanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/': {
      id: '/logistics/'
      path: '/logistics'
      fullPath: '/logistics/'
      preLoaderRoute: typeof LogisticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/release-areas': {
      id: '/logistics/release-areas'
      path: '/logistics/release-areas'
      fullPath: '/logistics/release-areas'
      preLoaderRoute: typeof LogisticsReleaseAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/': {
      id: '/master-data/'
      path: '/master-data'
      fullPath: '/master-data/'
      preLoaderRoute: typeof MasterDataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/classification': {
      id: '/master-data/classification'
      path: '/master-data/classification'
      fullPath: '/master-data/classification'
      preLoaderRoute: typeof MasterDataClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/imports': {
      id: '/master-data/imports'
      path: '/master-data/imports'
      fullPath: '/master-data/imports'
      preLoaderRoute: typeof MasterDataImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/item-supply': {
      id: '/master-data/item-supply'
      path: '/master-data/item-supply'
      fullPath: '/master-data/item-supply'
      preLoaderRoute: typeof MasterDataItemSupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/assurance': {
      id: '/operations/assurance'
      path: '/operations/assurance'
      fullPath: '/operations/assurance'
      preLoaderRoute: typeof OperationsAssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/continuity': {
      id: '/operations/continuity'
      path: '/operations/continuity'
      fullPath: '/operations/continuity'
      preLoaderRoute: typeof OperationsContinuityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/cutover': {
      id: '/operations/cutover'
      path: '/operations/cutover'
      fullPath: '/operations/cutover'
      preLoaderRoute: typeof OperationsCutoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/devices': {
      id: '/operations/devices'
      path: '/operations/devices'
      fullPath: '/operations/devices'
      preLoaderRoute: typeof OperationsDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/integrations': {
      id: '/operations/integrations'
      path: '/operations/integrations'
      fullPath: '/operations/integrations'
      preLoaderRoute: typeof OperationsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/jobs': {
      id: '/operations/jobs'
      path: '/operations/jobs'
      fullPath: '/operations/jobs'
      preLoaderRoute: typeof OperationsJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/output': {
      id: '/operations/output'
      path: '/operations/output'
      fullPath: '/operations/output'
      preLoaderRoute: typeof OperationsOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/': {
      id: '/planning/'
      path: '/planning'
      fullPath: '/planning/'
      preLoaderRoute: typeof PlanningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/': {
      id: '/procurement/'
      path: '/procurement'
      fullPath: '/procurement/'
      preLoaderRoute: typeof ProcurementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/': {
      id: '/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/': {
      id: '/quality/'
      path: '/quality'
      fullPath: '/quality/'
      preLoaderRoute: typeof QualityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/': {
      id: '/reporting/'
      path: '/reporting'
      fullPath: '/reporting/'
      preLoaderRoute: typeof ReportingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/distribution': {
      id: '/reporting/distribution'
      path: '/reporting/distribution'
      fullPath: '/reporting/distribution'
      preLoaderRoute: typeof ReportingDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/reproducibility': {
      id: '/reporting/reproducibility'
      path: '/reporting/reproducibility'
      fullPath: '/reporting/reproducibility'
      preLoaderRoute: typeof ReportingReproducibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeviceRoute: DeviceRoute,
  HelpRoute: HelpRoute,
  NotificationsRoute: NotificationsRoute,
  PlatformRoute: PlatformRoute,
  ProductRoute: ProductRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  AdministrationAccessibilityRoute: AdministrationAccessibilityRoute,
  AdministrationAdoptionRoute: AdministrationAdoptionRoute,
  AdministrationAuditRoute: AdministrationAuditRoute,
  AdministrationCommercialRoute: AdministrationCommercialRoute,
  AdministrationConfigurationRoute: AdministrationConfigurationRoute,
  AdministrationErasureRoute: AdministrationErasureRoute,
  AdministrationOnboardingRoute: AdministrationOnboardingRoute,
  AdministrationOrganisationRoute: AdministrationOrganisationRoute,
  AdministrationPacksRoute: AdministrationPacksRoute,
  AdministrationPermissionsRoute: AdministrationPermissionsRoute,
  AdministrationTenantRoute: AdministrationTenantRoute,
  AdministrationTerminologyRoute: AdministrationTerminologyRoute,
  CommercialPriceBookRoute: CommercialPriceBookRoute,
  CommercialQuotesRoute: CommercialQuotesRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  FinanceAccountDeterminationRoute: FinanceAccountDeterminationRoute,
  LogisticsReleaseAreasRoute: LogisticsReleaseAreasRoute,
  MasterDataClassificationRoute: MasterDataClassificationRoute,
  MasterDataImportsRoute: MasterDataImportsRoute,
  MasterDataItemSupplyRoute: MasterDataItemSupplyRoute,
  OperationsAssuranceRoute: OperationsAssuranceRoute,
  OperationsContinuityRoute: OperationsContinuityRoute,
  OperationsCutoverRoute: OperationsCutoverRoute,
  OperationsDevicesRoute: OperationsDevicesRoute,
  OperationsIntegrationsRoute: OperationsIntegrationsRoute,
  OperationsJobsRoute: OperationsJobsRoute,
  OperationsOutputRoute: OperationsOutputRoute,
  ReportingDistributionRoute: ReportingDistributionRoute,
  ReportingReproducibilityRoute: ReportingReproducibilityRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  GovernanceIndexRoute: GovernanceIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  LogisticsIndexRoute: LogisticsIndexRoute,
  MasterDataIndexRoute: MasterDataIndexRoute,
  PlanningIndexRoute: PlanningIndexRoute,
  ProcurementIndexRoute: ProcurementIndexRoute,
  ProductionIndexRoute: ProductionIndexRoute,
  QualityIndexRoute: QualityIndexRoute,
  ReportingIndexRoute: ReportingIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
