/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ProductRouteImport } from './routes/product'
import { Route as AdministrationAuditRouteImport } from './routes/administration/audit'
import { Route as AdministrationConfigurationRouteImport } from './routes/administration/configuration'
import { Route as AdministrationOrganisationRouteImport } from './routes/administration/organisation'
import { Route as AdministrationPermissionsRouteImport } from './routes/administration/permissions'
import { Route as AdministrationTenantRouteImport } from './routes/administration/tenant'
import { Route as AdministrationTerminologyRouteImport } from './routes/administration/terminology'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents/$documentId'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as FinanceAccountDeterminationRouteImport } from './routes/finance/account-determination'
import { Route as GovernanceIndexRouteImport } from './routes/governance/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as LogisticsIndexRouteImport } from './routes/logistics/index'
import { Route as LogisticsReleaseAreasRouteImport } from './routes/logistics/release-areas'
import { Route as MasterDataIndexRouteImport } from './routes/master-data/index'
import { Route as MasterDataClassificationRouteImport } from './routes/master-data/classification'
import { Route as MasterDataImportsRouteImport } from './routes/master-data/imports'
import { Route as MasterDataItemSupplyRouteImport } from './routes/master-data/item-supply'
import { Route as OperationsAssuranceRouteImport } from './routes/operations/assurance'
import { Route as OperationsIntegrationsRouteImport } from './routes/operations/integrations'
import { Route as OperationsJobsRouteImport } from './routes/operations/jobs'
import { Route as PlanningIndexRouteImport } from './routes/planning/index'
import { Route as ProcurementIndexRouteImport } from './routes/procurement/index'
import { Route as ProductionIndexRouteImport } from './routes/production/index'
import { Route as QualityIndexRouteImport } from './routes/quality/index'
import { Route as ReportingIndexRouteImport } from './routes/reporting/index'
import { Route as SalesIndexRouteImport } from './routes/sales/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationAuditRoute = AdministrationAuditRouteImport.update({
  id: '/administration/audit',
  path: '/administration/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationConfigurationRoute =
  AdministrationConfigurationRouteImport.update({
    id: '/administration/configuration',
    path: '/administration/configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationOrganisationRoute =
  AdministrationOrganisationRouteImport.update({
    id: '/administration/organisation',
    path: '/administration/organisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationPermissionsRoute =
  AdministrationPermissionsRouteImport.update({
    id: '/administration/permissions',
    path: '/administration/permissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationTenantRoute = AdministrationTenantRouteImport.update({
  id: '/administration/tenant',
  path: '/administration/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationTerminologyRoute =
  AdministrationTerminologyRouteImport.update({
    id: '/administration/terminology',
    path: '/administration/terminology',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAccountDeterminationRoute =
  FinanceAccountDeterminationRouteImport.update({
    id: '/finance/account-determination',
    path: '/finance/account-determination',
    getParentRoute: () => rootRouteImport,
  } as any)
const GovernanceIndexRoute = GovernanceIndexRouteImport.update({
  id: '/governance/',
  path: '/governance/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsIndexRoute = LogisticsIndexRouteImport.update({
  id: '/logistics/',
  path: '/logistics/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsReleaseAreasRoute = LogisticsReleaseAreasRouteImport.update({
  id: '/logistics/release-areas',
  path: '/logistics/release-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataIndexRoute = MasterDataIndexRouteImport.update({
  id: '/master-data/',
  path: '/master-data/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataClassificationRoute =
  MasterDataClassificationRouteImport.update({
    id: '/master-data/classification',
    path: '/master-data/classification',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterDataImportsRoute = MasterDataImportsRouteImport.update({
  id: '/master-data/imports',
  path: '/master-data/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataItemSupplyRoute = MasterDataItemSupplyRouteImport.update({
  id: '/master-data/item-supply',
  path: '/master-data/item-supply',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsAssuranceRoute = OperationsAssuranceRouteImport.update({
  id: '/operations/assurance',
  path: '/operations/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIntegrationsRoute = OperationsIntegrationsRouteImport.update({
  id: '/operations/integrations',
  path: '/operations/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsJobsRoute = OperationsJobsRouteImport.update({
  id: '/operations/jobs',
  path: '/operations/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningIndexRoute = PlanningIndexRouteImport.update({
  id: '/planning/',
  path: '/planning/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementIndexRoute = ProcurementIndexRouteImport.update({
  id: '/procurement/',
  path: '/procurement/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityIndexRoute = QualityIndexRouteImport.update({
  id: '/quality/',
  path: '/quality/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingIndexRoute = ReportingIndexRouteImport.update({
  id: '/reporting/',
  path: '/reporting/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform': typeof PlatformRoute
  '/product': typeof ProductRoute
  '/administration/audit': typeof AdministrationAuditRoute
  '/administration/configuration': typeof AdministrationConfigurationRoute
  '/administration/organisation': typeof AdministrationOrganisationRoute
  '/administration/permissions': typeof AdministrationPermissionsRoute
  '/administration/tenant': typeof AdministrationTenantRoute
  '/administration/terminology': typeof AdministrationTerminologyRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/finance/account-determination': typeof FinanceAccountDeterminationRoute
  '/logistics/release-areas': typeof LogisticsReleaseAreasRoute
  '/master-data/classification': typeof MasterDataClassificationRoute
  '/master-data/imports': typeof MasterDataImportsRoute
  '/master-data/item-supply': typeof MasterDataItemSupplyRoute
  '/operations/assurance': typeof OperationsAssuranceRoute
  '/operations/integrations': typeof OperationsIntegrationsRoute
  '/operations/jobs': typeof OperationsJobsRoute
  '/finance/': typeof FinanceIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/master-data/': typeof MasterDataIndexRoute
  '/planning/': typeof PlanningIndexRoute
  '/procurement/': typeof ProcurementIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/quality/': typeof QualityIndexRoute
  '/reporting/': typeof ReportingIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platform': typeof PlatformRoute
  '/product': typeof ProductRoute
  '/administration/audit': typeof AdministrationAuditRoute
  '/administration/configuration': typeof AdministrationConfigurationRoute
  '/administration/organisation': typeof AdministrationOrganisationRoute
  '/administration/permissions': typeof AdministrationPermissionsRoute
  '/administration/tenant': typeof AdministrationTenantRoute
  '/administration/terminology': typeof AdministrationTerminologyRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/finance/account-determination': typeof FinanceAccountDeterminationRoute
  '/logistics/release-areas': typeof LogisticsReleaseAreasRoute
  '/master-data/classification': typeof MasterDataClassificationRoute
  '/master-data/imports': typeof MasterDataImportsRoute
  '/master-data/item-supply': typeof MasterDataItemSupplyRoute
  '/operations/assurance': typeof OperationsAssuranceRoute
  '/operations/integrations': typeof OperationsIntegrationsRoute
  '/operations/jobs': typeof OperationsJobsRoute
  '/finance': typeof FinanceIndexRoute
  '/governance': typeof GovernanceIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/logistics': typeof LogisticsIndexRoute
  '/master-data': typeof MasterDataIndexRoute
  '/planning': typeof PlanningIndexRoute
  '/procurement': typeof ProcurementIndexRoute
  '/production': typeof ProductionIndexRoute
  '/quality': typeof QualityIndexRoute
  '/reporting': typeof ReportingIndexRoute
  '/sales': typeof SalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/platform': typeof PlatformRoute
  '/product': typeof ProductRoute
  '/administration/audit': typeof AdministrationAuditRoute
  '/administration/configuration': typeof AdministrationConfigurationRoute
  '/administration/organisation': typeof AdministrationOrganisationRoute
  '/administration/permissions': typeof AdministrationPermissionsRoute
  '/administration/tenant': typeof AdministrationTenantRoute
  '/administration/terminology': typeof AdministrationTerminologyRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/finance/account-determination': typeof FinanceAccountDeterminationRoute
  '/logistics/release-areas': typeof LogisticsReleaseAreasRoute
  '/master-data/classification': typeof MasterDataClassificationRoute
  '/master-data/imports': typeof MasterDataImportsRoute
  '/master-data/item-supply': typeof MasterDataItemSupplyRoute
  '/operations/assurance': typeof OperationsAssuranceRoute
  '/operations/integrations': typeof OperationsIntegrationsRoute
  '/operations/jobs': typeof OperationsJobsRoute
  '/finance/': typeof FinanceIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/master-data/': typeof MasterDataIndexRoute
  '/planning/': typeof PlanningIndexRoute
  '/procurement/': typeof ProcurementIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/quality/': typeof QualityIndexRoute
  '/reporting/': typeof ReportingIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/platform'
    | '/product'
    | '/administration/audit'
    | '/administration/configuration'
    | '/administration/organisation'
    | '/administration/permissions'
    | '/administration/tenant'
    | '/administration/terminology'
    | '/documents/$documentId'
    | '/finance/account-determination'
    | '/logistics/release-areas'
    | '/master-data/classification'
    | '/master-data/imports'
    | '/master-data/item-supply'
    | '/operations/assurance'
    | '/operations/integrations'
    | '/operations/jobs'
    | '/finance/'
    | '/governance/'
    | '/inventory/'
    | '/logistics/'
    | '/master-data/'
    | '/planning/'
    | '/procurement/'
    | '/production/'
    | '/quality/'
    | '/reporting/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/platform'
    | '/product'
    | '/administration/audit'
    | '/administration/configuration'
    | '/administration/organisation'
    | '/administration/permissions'
    | '/administration/tenant'
    | '/administration/terminology'
    | '/documents/$documentId'
    | '/finance/account-determination'
    | '/logistics/release-areas'
    | '/master-data/classification'
    | '/master-data/imports'
    | '/master-data/item-supply'
    | '/operations/assurance'
    | '/operations/integrations'
    | '/operations/jobs'
    | '/finance'
    | '/governance'
    | '/inventory'
    | '/logistics'
    | '/master-data'
    | '/planning'
    | '/procurement'
    | '/production'
    | '/quality'
    | '/reporting'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/platform'
    | '/product'
    | '/administration/audit'
    | '/administration/configuration'
    | '/administration/organisation'
    | '/administration/permissions'
    | '/administration/tenant'
    | '/administration/terminology'
    | '/documents/$documentId'
    | '/finance/account-determination'
    | '/logistics/release-areas'
    | '/master-data/classification'
    | '/master-data/imports'
    | '/master-data/item-supply'
    | '/operations/assurance'
    | '/operations/integrations'
    | '/operations/jobs'
    | '/finance/'
    | '/governance/'
    | '/inventory/'
    | '/logistics/'
    | '/master-data/'
    | '/planning/'
    | '/procurement/'
    | '/production/'
    | '/quality/'
    | '/reporting/'
    | '/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlatformRoute: typeof PlatformRoute
  ProductRoute: typeof ProductRoute
  AdministrationAuditRoute: typeof AdministrationAuditRoute
  AdministrationConfigurationRoute: typeof AdministrationConfigurationRoute
  AdministrationOrganisationRoute: typeof AdministrationOrganisationRoute
  AdministrationPermissionsRoute: typeof AdministrationPermissionsRoute
  AdministrationTenantRoute: typeof AdministrationTenantRoute
  AdministrationTerminologyRoute: typeof AdministrationTerminologyRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  FinanceAccountDeterminationRoute: typeof FinanceAccountDeterminationRoute
  LogisticsReleaseAreasRoute: typeof LogisticsReleaseAreasRoute
  MasterDataClassificationRoute: typeof MasterDataClassificationRoute
  MasterDataImportsRoute: typeof MasterDataImportsRoute
  MasterDataItemSupplyRoute: typeof MasterDataItemSupplyRoute
  OperationsAssuranceRoute: typeof OperationsAssuranceRoute
  OperationsIntegrationsRoute: typeof OperationsIntegrationsRoute
  OperationsJobsRoute: typeof OperationsJobsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  GovernanceIndexRoute: typeof GovernanceIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  LogisticsIndexRoute: typeof LogisticsIndexRoute
  MasterDataIndexRoute: typeof MasterDataIndexRoute
  PlanningIndexRoute: typeof PlanningIndexRoute
  ProcurementIndexRoute: typeof ProcurementIndexRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
  QualityIndexRoute: typeof QualityIndexRoute
  ReportingIndexRoute: typeof ReportingIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/audit': {
      id: '/administration/audit'
      path: '/administration/audit'
      fullPath: '/administration/audit'
      preLoaderRoute: typeof AdministrationAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/configuration': {
      id: '/administration/configuration'
      path: '/administration/configuration'
      fullPath: '/administration/configuration'
      preLoaderRoute: typeof AdministrationConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/organisation': {
      id: '/administration/organisation'
      path: '/administration/organisation'
      fullPath: '/administration/organisation'
      preLoaderRoute: typeof AdministrationOrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/permissions': {
      id: '/administration/permissions'
      path: '/administration/permissions'
      fullPath: '/administration/permissions'
      preLoaderRoute: typeof AdministrationPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/tenant': {
      id: '/administration/tenant'
      path: '/administration/tenant'
      fullPath: '/administration/tenant'
      preLoaderRoute: typeof AdministrationTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/terminology': {
      id: '/administration/terminology'
      path: '/administration/terminology'
      fullPath: '/administration/terminology'
      preLoaderRoute: typeof AdministrationTerminologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/account-determination': {
      id: '/finance/account-determination'
      path: '/finance/account-determination'
      fullPath: '/finance/account-determination'
      preLoaderRoute: typeof FinanceAccountDeterminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/': {
      id: '/governance/'
      path: '/governance'
      fullPath: '/governance/'
      preLoaderRoute: typeof GovernanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/': {
      id: '/logistics/'
      path: '/logistics'
      fullPath: '/logistics/'
      preLoaderRoute: typeof LogisticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/release-areas': {
      id: '/logistics/release-areas'
      path: '/logistics/release-areas'
      fullPath: '/logistics/release-areas'
      preLoaderRoute: typeof LogisticsReleaseAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/': {
      id: '/master-data/'
      path: '/master-data'
      fullPath: '/master-data/'
      preLoaderRoute: typeof MasterDataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/classification': {
      id: '/master-data/classification'
      path: '/master-data/classification'
      fullPath: '/master-data/classification'
      preLoaderRoute: typeof MasterDataClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/imports': {
      id: '/master-data/imports'
      path: '/master-data/imports'
      fullPath: '/master-data/imports'
      preLoaderRoute: typeof MasterDataImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/item-supply': {
      id: '/master-data/item-supply'
      path: '/master-data/item-supply'
      fullPath: '/master-data/item-supply'
      preLoaderRoute: typeof MasterDataItemSupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/assurance': {
      id: '/operations/assurance'
      path: '/operations/assurance'
      fullPath: '/operations/assurance'
      preLoaderRoute: typeof OperationsAssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/integrations': {
      id: '/operations/integrations'
      path: '/operations/integrations'
      fullPath: '/operations/integrations'
      preLoaderRoute: typeof OperationsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/jobs': {
      id: '/operations/jobs'
      path: '/operations/jobs'
      fullPath: '/operations/jobs'
      preLoaderRoute: typeof OperationsJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/': {
      id: '/planning/'
      path: '/planning'
      fullPath: '/planning/'
      preLoaderRoute: typeof PlanningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/': {
      id: '/procurement/'
      path: '/procurement'
      fullPath: '/procurement/'
      preLoaderRoute: typeof ProcurementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/': {
      id: '/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/': {
      id: '/quality/'
      path: '/quality'
      fullPath: '/quality/'
      preLoaderRoute: typeof QualityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/': {
      id: '/reporting/'
      path: '/reporting'
      fullPath: '/reporting/'
      preLoaderRoute: typeof ReportingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlatformRoute: PlatformRoute,
  ProductRoute: ProductRoute,
  AdministrationAuditRoute: AdministrationAuditRoute,
  AdministrationConfigurationRoute: AdministrationConfigurationRoute,
  AdministrationOrganisationRoute: AdministrationOrganisationRoute,
  AdministrationPermissionsRoute: AdministrationPermissionsRoute,
  AdministrationTenantRoute: AdministrationTenantRoute,
  AdministrationTerminologyRoute: AdministrationTerminologyRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  FinanceAccountDeterminationRoute: FinanceAccountDeterminationRoute,
  LogisticsReleaseAreasRoute: LogisticsReleaseAreasRoute,
  MasterDataClassificationRoute: MasterDataClassificationRoute,
  MasterDataImportsRoute: MasterDataImportsRoute,
  MasterDataItemSupplyRoute: MasterDataItemSupplyRoute,
  OperationsAssuranceRoute: OperationsAssuranceRoute,
  OperationsIntegrationsRoute: OperationsIntegrationsRoute,
  OperationsJobsRoute: OperationsJobsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  GovernanceIndexRoute: GovernanceIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  LogisticsIndexRoute: LogisticsIndexRoute,
  MasterDataIndexRoute: MasterDataIndexRoute,
  PlanningIndexRoute: PlanningIndexRoute,
  ProcurementIndexRoute: ProcurementIndexRoute,
  ProductionIndexRoute: ProductionIndexRoute,
  QualityIndexRoute: QualityIndexRoute,
  ReportingIndexRoute: ReportingIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
