/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductRouteImport } from './routes/product'
import { Route as AdministrationConfigurationRouteImport } from './routes/administration/configuration'
import { Route as AdministrationPermissionsRouteImport } from './routes/administration/permissions'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents/$documentId'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as MasterDataIndexRouteImport } from './routes/master-data/index'
import { Route as OperationsAssuranceRouteImport } from './routes/operations/assurance'
import { Route as OperationsIntegrationsRouteImport } from './routes/operations/integrations'
import { Route as OperationsJobsRouteImport } from './routes/operations/jobs'
import { Route as PlanningIndexRouteImport } from './routes/planning/index'
import { Route as ProcurementIndexRouteImport } from './routes/procurement/index'
import { Route as SalesIndexRouteImport } from './routes/sales/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationConfigurationRoute =
  AdministrationConfigurationRouteImport.update({
    id: '/administration/configuration',
    path: '/administration/configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrationPermissionsRoute =
  AdministrationPermissionsRouteImport.update({
    id: '/administration/permissions',
    path: '/administration/permissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataIndexRoute = MasterDataIndexRouteImport.update({
  id: '/master-data/',
  path: '/master-data/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsAssuranceRoute = OperationsAssuranceRouteImport.update({
  id: '/operations/assurance',
  path: '/operations/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIntegrationsRoute = OperationsIntegrationsRouteImport.update({
  id: '/operations/integrations',
  path: '/operations/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsJobsRoute = OperationsJobsRouteImport.update({
  id: '/operations/jobs',
  path: '/operations/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningIndexRoute = PlanningIndexRouteImport.update({
  id: '/planning/',
  path: '/planning/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementIndexRoute = ProcurementIndexRouteImport.update({
  id: '/procurement/',
  path: '/procurement/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product': typeof ProductRoute
  '/administration/configuration': typeof AdministrationConfigurationRoute
  '/administration/permissions': typeof AdministrationPermissionsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/operations/assurance': typeof OperationsAssuranceRoute
  '/operations/integrations': typeof OperationsIntegrationsRoute
  '/operations/jobs': typeof OperationsJobsRoute
  '/finance/': typeof FinanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/master-data/': typeof MasterDataIndexRoute
  '/planning/': typeof PlanningIndexRoute
  '/procurement/': typeof ProcurementIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product': typeof ProductRoute
  '/administration/configuration': typeof AdministrationConfigurationRoute
  '/administration/permissions': typeof AdministrationPermissionsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/operations/assurance': typeof OperationsAssuranceRoute
  '/operations/integrations': typeof OperationsIntegrationsRoute
  '/operations/jobs': typeof OperationsJobsRoute
  '/finance': typeof FinanceIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/master-data': typeof MasterDataIndexRoute
  '/planning': typeof PlanningIndexRoute
  '/procurement': typeof ProcurementIndexRoute
  '/sales': typeof SalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product': typeof ProductRoute
  '/administration/configuration': typeof AdministrationConfigurationRoute
  '/administration/permissions': typeof AdministrationPermissionsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/operations/assurance': typeof OperationsAssuranceRoute
  '/operations/integrations': typeof OperationsIntegrationsRoute
  '/operations/jobs': typeof OperationsJobsRoute
  '/finance/': typeof FinanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/master-data/': typeof MasterDataIndexRoute
  '/planning/': typeof PlanningIndexRoute
  '/procurement/': typeof ProcurementIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/product'
    | '/administration/configuration'
    | '/administration/permissions'
    | '/documents/$documentId'
    | '/operations/assurance'
    | '/operations/integrations'
    | '/operations/jobs'
    | '/finance/'
    | '/inventory/'
    | '/master-data/'
    | '/planning/'
    | '/procurement/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product'
    | '/administration/configuration'
    | '/administration/permissions'
    | '/documents/$documentId'
    | '/operations/assurance'
    | '/operations/integrations'
    | '/operations/jobs'
    | '/finance'
    | '/inventory'
    | '/master-data'
    | '/planning'
    | '/procurement'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/product'
    | '/administration/configuration'
    | '/administration/permissions'
    | '/documents/$documentId'
    | '/operations/assurance'
    | '/operations/integrations'
    | '/operations/jobs'
    | '/finance/'
    | '/inventory/'
    | '/master-data/'
    | '/planning/'
    | '/procurement/'
    | '/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductRoute: typeof ProductRoute
  AdministrationConfigurationRoute: typeof AdministrationConfigurationRoute
  AdministrationPermissionsRoute: typeof AdministrationPermissionsRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  OperationsAssuranceRoute: typeof OperationsAssuranceRoute
  OperationsIntegrationsRoute: typeof OperationsIntegrationsRoute
  OperationsJobsRoute: typeof OperationsJobsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  MasterDataIndexRoute: typeof MasterDataIndexRoute
  PlanningIndexRoute: typeof PlanningIndexRoute
  ProcurementIndexRoute: typeof ProcurementIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/configuration': {
      id: '/administration/configuration'
      path: '/administration/configuration'
      fullPath: '/administration/configuration'
      preLoaderRoute: typeof AdministrationConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/permissions': {
      id: '/administration/permissions'
      path: '/administration/permissions'
      fullPath: '/administration/permissions'
      preLoaderRoute: typeof AdministrationPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data/': {
      id: '/master-data/'
      path: '/master-data'
      fullPath: '/master-data/'
      preLoaderRoute: typeof MasterDataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/assurance': {
      id: '/operations/assurance'
      path: '/operations/assurance'
      fullPath: '/operations/assurance'
      preLoaderRoute: typeof OperationsAssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/integrations': {
      id: '/operations/integrations'
      path: '/operations/integrations'
      fullPath: '/operations/integrations'
      preLoaderRoute: typeof OperationsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/jobs': {
      id: '/operations/jobs'
      path: '/operations/jobs'
      fullPath: '/operations/jobs'
      preLoaderRoute: typeof OperationsJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/': {
      id: '/planning/'
      path: '/planning'
      fullPath: '/planning/'
      preLoaderRoute: typeof PlanningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/': {
      id: '/procurement/'
      path: '/procurement'
      fullPath: '/procurement/'
      preLoaderRoute: typeof ProcurementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductRoute: ProductRoute,
  AdministrationConfigurationRoute: AdministrationConfigurationRoute,
  AdministrationPermissionsRoute: AdministrationPermissionsRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  OperationsAssuranceRoute: OperationsAssuranceRoute,
  OperationsIntegrationsRoute: OperationsIntegrationsRoute,
  OperationsJobsRoute: OperationsJobsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  MasterDataIndexRoute: MasterDataIndexRoute,
  PlanningIndexRoute: PlanningIndexRoute,
  ProcurementIndexRoute: ProcurementIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
