-- =============================================================================
-- 20260927220223 — emptied; repaired by 20261001905000
--
-- This file was written through the Lovable editor on 27 September as
-- "20260929500000 — Open counts come first in the count-task door", and
-- deployed that night. It restated public.erp_count_tasks(integer) so that
-- open counts sort first, and it refused to run unless the door stood as
-- 20260928100000 left it.
--
-- Its version sorts before 20260927400000 and 20260928100000, the two
-- migrations whose door it restates. Live applied it after them, because the
-- deploy applies a late-arriving file wherever it arrives. A build from an
-- empty database applies it in version order, before them, and its own
-- anchor refused with CLOVEERP_ANCHOR_MOVED, so no build from empty could
-- finish.
--
-- Live has already run this file, so emptying it changes nothing there. The
-- ordering it made true is re-applied, in the right place in the order, by
-- 20261001905000_open_counts_come_first_where_the_order_allows.sql, and the
-- edit is registered in supabase/ci/migrations_edited.txt.
-- =============================================================================

select 1;
