-- =============================================================================
-- A pack change-set code that is not a race
--
-- CI failed on erp_test.assert_starter_pack_acceptance():
--
--   duplicate key value violates unique constraint "change_set_tenant_id_code_key"
--   DETAIL: Key (tenant_id, code)=(..., pack-base-20260901160316) already exists.
--
-- erp.apply_content_pack() derived its change-set code from
-- to_char(clock_timestamp(), 'YYYYMMDDHH24MISS') — second resolution — and
-- erp.change_set is UNIQUE (tenant_id, code). Applying the same pack to the same
-- organisation twice within one second therefore collides. The acceptance suite
-- applies 'base' twice by design, so whether the build passes has been a
-- question of how fast the runner is.
--
-- Latent since packs were built, and not caused by the change that exposed it:
-- adding a migration shifted the timing enough for both applications to land in
-- the same second. It failed here, so it is fixed here — a race that only shows
-- on fast hardware is worse than one that always shows.
--
-- Fix-forward, as this repository requires: a new migration redefining the
-- function, never an edit to the one that first created it. The definition below
-- was taken from the catalogue and patched programmatically; the diff is five
-- added comment lines and one expression widened, and nothing else.
-- =============================================================================

CREATE OR REPLACE FUNCTION erp.apply_content_pack(p_pack_code text, p_change_set_code text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_tenant  uuid := erp.require_tenant_id();
  cp        erp_ref.content_pack%rowtype;
  v_cs      uuid;
  v_code    text;
  r         record;
  n         integer := 0;
  v_block   text := '';
  v_open    integer;
begin
  select * into cp from erp_ref.content_pack where code = p_pack_code;
  if not found then
    raise exception 'ERPWARE_UNKNOWN_PACK: %', p_pack_code using errcode = '23503';
  end if;

  -- §11.3: conflicts surface BEFORE anything lands, which means before the
  -- change set exists rather than at promotion. A blocking conflict is one
  -- nothing downstream can resolve.
  for r in select * from erp.pack_conflicts(p_pack_code) where severity = 'blocking' loop
    v_block := v_block || format(E'  %s (%s)\n', r.conflict, r.reference);
  end loop;
  if v_block <> '' then
    raise exception E'ERPWARE_PACK_CONFLICT: % cannot be applied as it stands\n%',
      p_pack_code, v_block using errcode = '23514';
  end if;

  -- The timestamp alone is second-resolution, and erp.change_set is
  -- UNIQUE (tenant_id, code). Two applications of the same pack to the same
  -- organisation within one second therefore collided — which is exactly what
  -- the acceptance suite does, and what a fast CI runner made happen. A short
  -- random suffix keeps the code readable and stops it being a race.
  v_code := coalesce(p_change_set_code,
    format('pack-%s-%s-%s', p_pack_code,
           to_char(clock_timestamp(), 'YYYYMMDDHH24MISS'),
           substr(replace(gen_random_uuid()::text, '-', ''), 1, 6)));

  v_cs := erp.create_change_set(v_code,
    format('%s (%s)', cp.name, cp.version),
    format('%s Generated by erp.apply_content_pack; %s',
           cp.description, cp.provenance));

  for r in select * from erp.plan_content_pack(p_pack_code) loop
    perform erp.add_change_set_item(v_cs, r.object_kind, r.object_key,
                                    r.payload, r.operation, null,
                                    format('%s %s', p_pack_code, cp.version));
    n := n + 1;
  end loop;

  insert into erp.tenant_pack
    (tenant_id, pack_code, version, status, change_set_id, item_count)
  values (v_tenant, p_pack_code, cp.version, 'planned', v_cs, n);

  select count(*) into v_open
    from erp.pack_decisions(p_pack_code) where not answered;

  return jsonb_build_object(
    'pack', p_pack_code,
    'version', cp.version,
    'change_set_id', v_cs,
    'change_set_code', v_code,
    'items', n,
    -- Reported rather than refused. §11.4 refuses at promotion, and it refuses
    -- there so that somebody can preview the change set and see what the
    -- decisions are actually about before answering them.
    'open_decisions', v_open,
    'advisories', coalesce((select jsonb_agg(c.conflict)
                              from erp.pack_conflicts(p_pack_code) c
                             where c.severity = 'advisory'), '[]'::jsonb));
end;
$function$

;

-- Prove it: two applications of the same pack in the same statement, which is
-- the tightest the collision could ever be.
do $$
declare a text; b text;
begin
  a := format('pack-%s-%s-%s', 'base',
              to_char(clock_timestamp(), 'YYYYMMDDHH24MISS'),
              substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
  b := format('pack-%s-%s-%s', 'base',
              to_char(clock_timestamp(), 'YYYYMMDDHH24MISS'),
              substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
  if a = b then
    raise exception 'ERPWARE_PACK_CODE_STILL_COLLIDES: % equals %', a, b;
  end if;
end $$;
