-- ─────────────────────────────────────────────────────────────────────────────
-- A field label is a word somebody can change.
--
-- 20260904960000 closed the card headings. This closes the rest of the same
-- class: the words inside the forms. A field's label and its hint, an action's
-- button text, a dialog's title and description, the options in a select — all
-- of them are declared at the call site as data and rendered by the component
-- through ui(), so a grep for ui("…") never saw one of them.
--
-- 1,356 screen strings now, of which 357 had no row. That number is the honest
-- size of the gap: the terminology screen has been reporting drift over about
-- two thirds of what the app actually says.
--
-- Two things had to be true before seeding, and neither was:
--
--   1. A select's options were rendered raw while its label went through ui(),
--      so a form could offer a renameable "Kind of site" above a fixed
--      "Warehouse". InquiryBoard had always passed its choices through ui();
--      ActionDialog had not. Fixed in the same change.
--
--   2. Thirty-four strings used a word the glossary had already replaced —
--      "Item" for Product, "Party" for Business partner, "Entity" for Company,
--      "Account" for Nominal account, "posting class" for Accounting code,
--      "principal" for User, "tenant" for Organisation, "Determination matrix"
--      for Account determination. Those are field labels people read every
--      day. They are corrected in the source, not exempted here: seeding them
--      as they stood would have made the wrong word the renameable one and
--      erp.assert_vocabulary_aligned() would have refused the migration
--      anyway, which is the guard doing exactly its job.
--
-- The keys are computed by erp_ref.ui_key() for the reason the last one gives:
-- a key written by hand is a key ui() never asks for.
-- ─────────────────────────────────────────────────────────────────────────────

insert into erp_ref.resource (key, locale, value, description)
select erp_ref.ui_key(v.text), 'en', v.text,
       'A screen string declared at its call site and rendered through ui().'
  from (values
  ('#'),
  ('A LIKE pattern over event types, e.g. approval.% or release.printed.'),
  ('A code and a name are the minimum. Everything else is maintainable afterwards.'),
  ('A discount above this percentage on any line is routed for approval.'),
  ('A named person'),
  ('A new key is created, everything protected is re-encrypted under it, and the old key is destroyed. There is no way back to the old key afterwards.'),
  ('A preview never consumes a sequence number.'),
  ('A time of day, e.g. 06:00.'),
  ('Accepted symbologies'),
  ('Accounting code'),
  ('Accounting codes and the matrix that decides the nominal account and analysis — with a gap report and no suspense fallback.'),
  ('Activated'),
  ('Add a line to a wave'),
  ('Add a location'),
  ('Add a priced product'),
  ('Add a print route'),
  ('Add a report to a pack'),
  ('Add a scenario'),
  ('Add line'),
  ('Add or amend a code template'),
  ('Add or amend a determination rule'),
  ('Add or amend a marshalling area'),
  ('Add or amend a value'),
  ('Add or amend an accounting code'),
  ('Add or amend an axis'),
  ('Adopt the stocking policy the engine calculates for one product and site.'),
  ('Age untouched stock back to bulk'),
  ('Ageing (hours)'),
  ('Allocate the wave'),
  ('An IANA name, e.g. Europe/London.'),
  ('Announce'),
  ('Annual recurring revenue'),
  ('Apply my queued actions'),
  ('Apply wording'),
  ('Approval threshold'),
  ('Approved for use'),
  ('Archive only'),
  ('As at'),
  ('As entered'),
  ('Assemble a pack'),
  ('At'),
  ('At (HH:MM)'),
  ('Attach a document'),
  ('Audience'),
  ('Average contract value'),
  ('Batch code'),
  ('Batch controlled'),
  ('Build export'),
  ('Business partners'),
  ('Business partners and their accounting code'),
  ('Cadence'),
  ('Cancel window'),
  ('Casing'),
  ('Category'),
  ('Changes'),
  ('Check'),
  ('Churn, last 12 months'),
  ('Classification (JSON)'),
  ('Classify a product'),
  ('Clear a kill switch'),
  ('Code template'),
  ('Combine one batch into another of the same product and condition.'),
  ('Comma separated GS1 application identifiers, e.g. 01, 10, 17. Leave empty when any recognised barcode will do.'),
  ('Comma separated codes from the symbology list below, e.g. gs1_128, gs1_datamatrix.'),
  ('Comma separated. Leave empty for every exposed view.'),
  ('Comma separated. Leave empty to apply to every product.'),
  ('Comma separated. Leave empty to serve any product.'),
  ('Completeness and validity of business partner master records.'),
  ('Contact at a business partner'),
  ('Contain'),
  ('Contracts in force'),
  ('Control quantity'),
  ('Control total, minor units'),
  ('Cost basis by product and site, in minor units.'),
  ('Country'),
  ('Cover against policy, by product and site.'),
  ('Create'),
  ('Create a classified product'),
  ('Create a service user'),
  ('Create business partner'),
  ('Create product'),
  ('Create the contract'),
  ('Credential id'),
  ('Cut a domain over'),
  ('DKIM verified'),
  ('DMARC verified'),
  ('Daily'),
  ('Daily at a time'),
  ('Daily, weekly or monthly.'),
  ('Day of month'),
  ('Days of week'),
  ('Decide'),
  ('Declare'),
  ('Default stock'),
  ('Default supplier'),
  ('Defaults to UTC.'),
  ('Defaults to a year.'),
  ('Define a job'),
  ('Define a pack'),
  ('Define a route'),
  ('Delegate approvals'),
  ('Delegation — the original stays the approver of record'),
  ('Delivered by'),
  ('Department code'),
  ('Deprecate a contract on notice'),
  ('Description'),
  ('Designate'),
  ('Destroyed'),
  ('Detail'),
  ('Device code'),
  ('Digest every (minutes)'),
  ('Dimensions (JSON)'),
  ('Document id'),
  ('Domain'),
  ('Dots per inch, e.g. 203 or 300. Required for a label printer.'),
  ('Draft an amendment'),
  ('End a supplier relationship'),
  ('End cover'),
  ('Escalate after (minutes)'),
  ('Escalate to role'),
  ('Event pattern'),
  ('Every N seconds'),
  ('Every accounting code, transaction type and company combination with no rule behind it.'),
  ('Every axis answered for one product.'),
  ('Every nominal account with a movement, by ledger.'),
  ('Everyone holding a role'),
  ('Execute'),
  ('Expires'),
  ('Expose a governed view'),
  ('Fiscal year'),
  ('Flag as a security incident'),
  ('For an interval schedule. At least 30.'),
  ('Free text — finished_good, raw_material, packaging.'),
  ('From (local part)'),
  ('From the legacy report as at the same date: stock value, open balances, or trial balance debits.'),
  ('From value'),
  ('GBP, EUR…'),
  ('Gate printing on full allocation'),
  ('Group'),
  ('How far apart the two may be and still agree. Zero when blank.'),
  ('How is this product classified?'),
  ('How the print agent reaches it, e.g. a host and port or a queue name.'),
  ('In major units per term, for example 12000 for twelve thousand a year.'),
  ('Interval (seconds)'),
  ('Invite a person'),
  ('Invoice against an order'),
  ('JSON.'),
  ('Job code'),
  ('Kept with the decision. Reverting reopens the domain to loads and reversals.'),
  ('Kept with the request: a subject access request, a leaver, a legal instruction.'),
  ('Key'),
  ('Key version'),
  ('Kind of cover'),
  ('Kind of location'),
  ('Label'),
  ('Labels'),
  ('Language'),
  ('Lead time (days)'),
  ('Leave as tenant_data unless a separate key is in use.'),
  ('Leave empty for any template of the kind.'),
  ('Leave empty for the step''s default rule.'),
  ('Leave empty for the top band.'),
  ('Leave empty to apply your queued actions on every device. Only actions captured under your own session apply; anyone else''s are held for them.'),
  ('Leave empty to cover everything they approve.'),
  ('Leave empty unless one country posts differently.'),
  ('Leave empty unless the requirement is deliberately divided.'),
  ('Left empty, one is generated.'),
  ('Legacy figure, minor units'),
  ('Legal name'),
  ('Line reference'),
  ('Lower case'),
  ('Lower wins among equally specific routes.'),
  ('Mandatory identifiers'),
  ('Marshalling area'),
  ('Maximum'),
  ('May be retired after'),
  ('Me'),
  ('Message id'),
  ('Minimum margin'),
  ('Minimum order quantity'),
  ('Monthly recurring revenue'),
  ('Name affected organisations'),
  ('Named for the tool that will hold it, scoped to exposed views, and shown once.'),
  ('Nominal account'),
  ('Notes'),
  ('Numbering, lifecycle and approvals come from the type this organisation configured.'),
  ('Object identifier'),
  ('Off'),
  ('Only for a role subscription.'),
  ('Only for product classes'),
  ('Only when triggered'),
  ('Open a change request'),
  ('Open a mass change'),
  ('Open a wave'),
  ('Operational (alerts, reminders)'),
  ('Optional; a label for a document carries its number.'),
  ('Output kind'),
  ('Overage invoiced'),
  ('Permission'),
  ('Person id'),
  ('Policy code'),
  ('Post update'),
  ('Preference rank'),
  ('Preview'),
  ('Priority'),
  ('Product name'),
  ('Products'),
  ('Products and their accounting code'),
  ('Promise a date'),
  ('Proposed change'),
  ('Pull — move only what a wave is short'),
  ('Purpose'),
  ('Push — top up to the maximum'),
  ('Qualify a supplier'),
  ('Queue address'),
  ('Raise a customer return'),
  ('Raised'),
  ('Re-allocate a short wave'),
  ('Receive against an order'),
  ('Record DNS verification'),
  ('Record a deliberate override'),
  ('Record a parallel-run figure'),
  ('Record disclosure'),
  ('Record id'),
  ('Refuse'),
  ('Refused for yourself, for a subject with an open request, and for a subject already erased.'),
  ('Refused unless every load of the domain reconciles, a parallel-run figure on or after the latest load is within tolerance, and you are not the person who loaded it. The nominal ledger also needs migration clearing at zero.'),
  ('Register a device'),
  ('Register a printer'),
  ('Register a sending domain'),
  ('Release a credit hold'),
  ('Render a label'),
  ('Render id'),
  ('Renewal rate, last 12 months'),
  ('Repair'),
  ('Replace'),
  ('Replay a message'),
  ('Replenishment'),
  ('Reply-to'),
  ('Reprint'),
  ('Request an erasure'),
  ('Request deletion'),
  ('Requested'),
  ('Requested by'),
  ('Required'),
  ('Required date'),
  ('Required for a label printer.'),
  ('Reserve stock for a line'),
  ('Resolution'),
  ('Resolve'),
  ('Resolve a price'),
  ('Resolve a purchase price'),
  ('Result'),
  ('Retire a contract'),
  ('Retire a determination rule'),
  ('Retire an accounting code'),
  ('Revenue at risk'),
  ('Reverse'),
  ('Revert a cutover'),
  ('Revoke a credential'),
  ('Role'),
  ('Role code'),
  ('Roll back'),
  ('Rotate and destroy the old key'),
  ('Rotate the key'),
  ('Rotate this organisation''s encryption key'),
  ('Route code'),
  ('Rows'),
  ('Run go-live checks'),
  ('Runs'),
  ('SPF verified'),
  ('Seed a demo configuration'),
  ('Seed a demo organisation'),
  ('Segments (JSON)'),
  ('Selector'),
  ('Serial number'),
  ('Service level'),
  ('Set a kill switch'),
  ('Set a partner''s accounting code'),
  ('Set a product''s accounting code'),
  ('Set a scan rule'),
  ('Set or amend a supplier for a product'),
  ('Ship in full'),
  ('Sign and provision'),
  ('Sign the amendment'),
  ('Site (leave empty for everywhere)'),
  ('Site code'),
  ('Sourcing split (%)'),
  ('Stage opening balances'),
  ('Staged'),
  ('Standard rate'),
  ('Starting state'),
  ('Stock only: total units on the legacy report.'),
  ('Stock unit'),
  ('Subscribe to a report'),
  ('Substitution — the delegate takes the decision as their own'),
  ('Supplier''s own code'),
  ('Switch a route off or on'),
  ('Target'),
  ('Task'),
  ('Template code'),
  ('The chain a request of this value would take, and which rule chose each approver.'),
  ('The code of the site this device works at.'),
  ('The date the balances stand at. Every movement and journal is dated here.'),
  ('The label or paper stock loaded by default.'),
  ('The nominal account and analysis a posting would take, and the rule that chose it.'),
  ('The projected balance for one product and site across the horizon.'),
  ('The role given here is the first one; more can be added afterwards.'),
  ('The same code again replaces the scenario. A completion check the product does not have is refused.'),
  ('The same resolution replenishment and planning use, including the site override and the approval check.'),
  ('The wording of every label, per organisation.'),
  ('Their reference'),
  ('This wording applies to this organisation only, in this locale.'),
  ('Three-letter codes separated by commas, for example GBP, EUR.'),
  ('Timezone'),
  ('Tolerance, minor units'),
  ('Transactional (invoices, orders)'),
  ('Tried in the department first, then at company level.'),
  ('Trigger a job'),
  ('Two-letter code, e.g. GB.'),
  ('Unit price'),
  ('Up to value'),
  ('Updated'),
  ('Upper case'),
  ('User (someone who signs in)'),
  ('Validate'),
  ('View code'),
  ('View codes'),
  ('Weekly'),
  ('Weekly only. ISO numbers, 1 = Monday, comma separated.'),
  ('What can still be committed for one product at one site, on a date.'),
  ('What changes'),
  ('What code would this produce?'),
  ('What each company owes another, before elimination.'),
  ('What is not covered yet?'),
  ('What should this supplier charge for this product today, and on what basis?'),
  ('What the code template uses for this value.'),
  ('What the engine would set for one product and site, before adopting it.'),
  ('What the old system reports for this domain as at the date. Ours is computed when you record it.'),
  ('What the person is given before they begin.'),
  ('What they are asked to do, in the organisation''s own words.'),
  ('What would this customer pay for this product today?'),
  ('When one is missing'),
  ('Where it stands'),
  ('Where would this post?'),
  ('Which columns hold a person''s data and what erasure does to each; requests to erase a user or contact, executed by a second person, with the certificate.'),
  ('Who'),
  ('Who may practise it: procurement.receive, inventory.count, and so on.'),
  ('Who would this be bought from?'),
  ('Whoever owns the affected object'),
  ('Why this rule exists'),
  ('Witness'),
  ('Wording'),
  ('Workstation'),
  ('average business partner record score'),
  ('e.g. invoices'),
  ('product and site positions')
  ) as v(text)
on conflict (key, locale) do nothing;

select erp.assert_vocabulary_aligned();
select erp.assert_resource_coverage('en');
