-- The words the screens say that nobody could rename.
--
-- supabase/ci/screen_strings.sh collects every visible string the application
-- writes — ui("…") literals, the strings src/lib/modules.tsx declares, the
-- props of the panel components and the labels and hints of every form — and
-- refuses the build if one of them has no en row in erp_ref.resource, because
-- a string with no row is a string no organisation can rename. It has run
-- after the check catalogue since it was written, and no push since 6 September
-- got that far. PR 84 was the first, and the answer was 394 of 2085.
--
-- Most are this month's: the warehouse, forecast and audit screens, the finance
-- statements, the API access panel, the procurement flow's hints. 29 of
-- them have their exact text at en already, under a key somebody wrote by
-- hand — ui.stock_audit_*, nav.finance_statements and the like — which ui()
-- never asks for, because ui() asks for erp_ref.ui_key(text). Those words were
-- renameable on paper and not on the screen; they get the key the screen uses.
--
-- Two strings are not seeded as they stood. "Change set" and "start a new
-- change set" use the model term the glossary retired for Change (Terminology
-- §4), and erp.assert_vocabulary_aligned() refuses an internal term on any
-- surface but the glossary itself. They are corrected in the source — a
-- default field label in src/components/erp/actions-bar.tsx and a hint in
-- src/lib/modules.tsx — and the corrected words are what is seeded, for the
-- reason 20260904970000 gives: seeding the wrong word makes the wrong word the
-- renameable one.
--
-- The keys are computed by erp_ref.ui_key(), as 20260904710000 and every
-- seeding since have done. on conflict do nothing, because the only way a key
-- can already exist is with this exact value, and a description somebody
-- wrote is not improved by this one.

insert into erp_ref.resource (key, locale, value, description)
select erp_ref.ui_key(v.text), 'en', v.text,
       'Screen string found without a row on the first complete run of supabase/ci/screen_strings.sh: a literal, a declared module string, a panel prop, or a form label or hint.'
  from (values
    ('A code is short and permanent — LEE-WH, ADMIN, SALES. Retiring a cost centre sets it inactive; the postings that already carry it keep it.'),
    ('A complaint, a deviation, an excursion — anything that needs answering.'),
    ('A draft requisition goes to whoever approves at its value. Nothing is committed to a supplier until it comes back approved.'),
    ('A firmed order becomes a purchase order or a works order and leaves planning.'),
    ('A forecast nobody has agreed to is a spreadsheet. Signing it off is what plans use it.'),
    ('A name for the machine account, not a person.'),
    ('A pattern; * matches anything. Use * on its own for every event.'),
    ('A quotation the customer has accepted becomes an order. Every line still outstanding is carried across at the quoted price, and the order remembers the quotation it came from.'),
    ('A replay sends the original payload again as a new attempt. The first attempt stays in the log.'),
    ('A second pair of eyes. The proposer cannot approve their own run.'),
    ('A short code for the handset or terminal.'),
    ('A short code for the priced product.'),
    ('A short code for this job.'),
    ('A short code for this marshalling area.'),
    ('A short code for this pack of reports.'),
    ('A short code for this posting class.'),
    ('A short code for this price book.'),
    ('A short code for this rule.'),
    ('A short code for this training scenario.'),
    ('A short code people will pick from lists.'),
    ('A short line describing it, as it will appear in lists.'),
    ('A short name so you can recognise this later.'),
    ('A task per pallet, from goods-in to the location it belongs in.'),
    ('Accept the difference and correct the stock by it.'),
    ('Account detail'),
    ('Acting on'),
    ('Add a storage rule'),
    ('Add a webhook subscription'),
    ('Add or amend a cost centre'),
    ('Add subscription'),
    ('Address'),
    ('Affected stock has shipped: raise a recall and log every action against the clock.'),
    ('All cost centres'),
    ('Amend a location'),
    ('An approved requisition becomes an order to a supplier. Every line still outstanding is carried across, and the order remembers the requisition it came from — so a part order can be finished later.'),
    ('An approved requisition is the one thing that converts into a purchase order. Approving does not order anything by itself.'),
    ('An event closes when the disposition is made and the actions are logged.'),
    ('Anything the service account is not granted will be refused.'),
    ('Approve it'),
    ('Approve this requisition'),
    ('Ask a counting programme for its next set of places to count.'),
    ('Ask the warehouse to move what is standing in goods-in. A task is raised for each pallet in a receiving location at that site, sending it to the place the storage rules say the product belongs.'),
    ('Ask the warehouse to move what is standing in goods-in. A task is raised for each pallet sitting in a receiving location at that site; if nothing is standing there, nothing is raised.'),
    ('Assets'),
    ('Axis code'),
    ('Axis code to value code.'),
    ('Balance sheet'),
    ('Balances'),
    ('Balances by location'),
    ('Balances by product within a location'),
    ('Bill'),
    ('Bill what was delivered, take the cash in, pay what is owed out, then close the period.'),
    ('Bills of materials'),
    ('Block a location'),
    ('Book'),
    ('Book time'),
    ('Booking a shipment is the commitment the carrier sees.'),
    ('Cash in'),
    ('Charged by default for spend this department approves.'),
    ('Choose the service account the key acts as, and the permissions it may use.'),
    ('Closing an order settles its variance and stops further booking.'),
    ('Comment'),
    ('Complete a putaway'),
    ('Complete the task'),
    ('Component'),
    ('Confirm'),
    ('Consumable'),
    ('Convert to a purchase order'),
    ('Convert to a sales order'),
    ('Copy it from the credential listed on this page.'),
    ('Copy it from the render listed in Recent output on this page.'),
    ('Copy the id from the mass change listed on this page.'),
    ('Copy the id from the message shown in the backlog below.'),
    ('Correct'),
    ('Cost centres'),
    ('Cost of sales and expenses'),
    ('Count'),
    ('Count class'),
    ('Counting'),
    ('Counting a location, recording what was found, and posting the difference.'),
    ('Create and send'),
    ('Create the purchase order'),
    ('Create the sales order'),
    ('Decide an approval waiting on me'),
    ('Decision'),
    ('Define a bill of materials'),
    ('Delivered, or failed with a reason. Both are facts the customer will ask about.'),
    ('Delivery'),
    ('Demand'),
    ('Demand against supply, netted, exploded through the bills of material.'),
    ('Demand per period, from history and from what you know that history does not.'),
    ('Despatch, step by step'),
    ('Device step'),
    ('Disabled'),
    ('Discontinued'),
    ('Document type'),
    ('Draft'),
    ('Ending a key'),
    ('Equity'),
    ('Event'),
    ('Events'),
    ('Events matching the pattern are posted to this address, signed with a secret shown once.'),
    ('Every location with its quantity and value, the last count against it, and the variance between the two.'),
    ('Everything one run is made of, with the quantity of each it uses.'),
    ('Fill to'),
    ('Fill to at most'),
    ('Finished good'),
    ('Finished quantity, and scrap, back into stock.'),
    ('Firm'),
    ('Forecast'),
    ('Forecast the demand, sign it off, run the requirements, then firm what the run suggests.'),
    ('Give a place a parent to nest it — a bin inside an aisle inside a zone. A place that is not pickable is reserve: stock stands there, but pickers are not sent to it.'),
    ('Goods arrive, are put away, are counted, and are corrected or handed on. Each box is where work waits; the button is what moves it.'),
    ('Goods in'),
    ('Groups under'),
    ('Hand on'),
    ('Hide account detail'),
    ('Holds'),
    ('Holds at most'),
    ('How people will refer to this partner everywhere.'),
    ('How people will refer to this product everywhere.'),
    ('How serious this is, in your own scheme.'),
    ('How the figures were worked out'),
    ('How this key is recognised in the list and the audit log.'),
    ('In use from'),
    ('In use until'),
    ('Income'),
    ('Inspect'),
    ('Invoice'),
    ('Issue an API key'),
    ('Issue key'),
    ('Kept permanently against the amendment.'),
    ('Kept with the record for whoever reads it later.'),
    ('Kind of place'),
    ('Last counted'),
    ('Lead-time demand'),
    ('Leave blank to let the system number it.'),
    ('Leave empty to keep the name it has.'),
    ('Leave empty to serve every channel.'),
    ('Leave empty to serve every order type.'),
    ('Leave empty unless one reason posts differently.'),
    ('Leave unchosen to apply the policy across the whole company.'),
    ('Leave unchosen to apply the policy at every site.'),
    ('Leave unchosen to start a new change for this proposal.'),
    ('Left blank, a new product starts active.'),
    ('Liabilities'),
    ('Limits the policy to one handheld step, such as picking or goods-in.'),
    ('Locations and bins'),
    ('Looking after a subscription'),
    ('Lower is tried first. 100 unless you say otherwise.'),
    ('Machine accounts only. Create one on Administration → Permissions.'),
    ('Maintain cost centres'),
    ('Makes'),
    ('Making, step by step'),
    ('Measured over'),
    ('Money received, applied against the invoices it settles.'),
    ('Money, step by step'),
    ('More roles can be added afterwards.'),
    ('Multiple'),
    ('Must be https. The signature is in the request headers.'),
    ('Name a product, or a product class, or neither — a rule naming the product beats a rule naming its class, which beats a rule naming everything. Lower priority numbers are tried first.'),
    ('Name it for the tool that will hold it.'),
    ('No account moved on these filters.'),
    ('No bills of materials yet. Define one with the action above before raising a works order for a made product.'),
    ('No cost centre yet. Every site and department already here becomes one as soon as you add it above.'),
    ('No deliveries received yet, so the planned lead time is used'),
    ('No supplier'),
    ('No supplier is set up for this product'),
    ('Nothing is put away to a blocked place and nothing is picked from it. The stock standing in it stays where it is.'),
    ('Nothing measured yet, so there is nothing to explain.'),
    ('Nothing posted to the balance sheet yet.'),
    ('Obsolete'),
    ('On order'),
    ('One row per axis: the axis code and the value code chosen for it.'),
    ('One run makes'),
    ('Only if this customer already runs their own organisation here.'),
    ('Only needed when skipping the task rather than completing it.'),
    ('Only when the audience is a department.'),
    ('Only when the audience is one named person.'),
    ('Operation time against the route, so the variance means something.'),
    ('Optional. From the label on the device.'),
    ('Optional. Helps the floor recognise the wave.'),
    ('Optional. Kept on the approval record.'),
    ('Optional. Kept permanently against the cutover.'),
    ('Optional. Kept with the quote.'),
    ('Optional. Kept with the record.'),
    ('Optional. Leave empty for a key that runs until it is revoked.'),
    ('Optional. Leave empty to use the product''s usual rule.'),
    ('Optional. Left empty, one is generated.'),
    ('Optional. Once the place holds this much, the next rule is used.'),
    ('Optional. Overrides the product''s own wording on this line.'),
    ('Optional. Put-away skips a place that is already full.'),
    ('Optional. Recorded against the run.'),
    ('Optional. Shown on quotes.'),
    ('Optional. Shown to whoever approves this.'),
    ('Optional. The code is what people scan.'),
    ('Optional. The consignment or tracking number.'),
    ('Optional. The line number this override applies to.'),
    ('Optional. The pallet or tote this line must ship on.'),
    ('Optional. The wording used for the message.'),
    ('Optional. Use it to group values into a tree.'),
    ('Optional. Use it to roll several cost centres into one heading.'),
    ('Optional. Useful when a product has more than one way of being made.'),
    ('Optional. What the capacity above is counted in.'),
    ('Optional. Where the legacy figure came from.'),
    ('Optional. Why this price book exists.'),
    ('Order by'),
    ('Order qty'),
    ('Order up to'),
    ('Out by'),
    ('Over'),
    ('Packaging'),
    ('Pause or resume'),
    ('Paused'),
    ('Pausing stops delivery without losing the history. Rotating replaces the signing secret immediately.'),
    ('Pay'),
    ('Paying an approved run clears the payable and credits the bank.'),
    ('Period close: the task list, then the close itself.'),
    ('Pick face'),
    ('Pick the order'),
    ('Picked goods waiting to leave. A delivery is what a shipment carries.'),
    ('Place'),
    ('Place blocked'),
    ('Plan the shipment, choose the carrier, book it, then confirm what arrived.'),
    ('Plan, step by step'),
    ('Planned order'),
    ('Posted lines'),
    ('Profit and balance sheet'),
    ('Profit and loss'),
    ('Proof'),
    ('Put away'),
    ('Quality, step by step'),
    ('Raise a purchase order'),
    ('Raise tasks from a counting programme, record what was found, then post it. Posting is what moves the stock: until then the count is an observation, not a correction.'),
    ('Raise the order, release it to the floor, issue the components, book the time, receive the output and close it.'),
    ('Raise the tasks'),
    ('Raw material'),
    ('Reading the journals…'),
    ('Receipts posted against a purchase order. Stock lands in goods-in before it has a home.'),
    ('Record being kept'),
    ('Record being withdrawn'),
    ('Record the decision'),
    ('Recorded against the key and in the audit log.'),
    ('Recorded permanently against the key.'),
    ('Recorded permanently against the replay.'),
    ('Recorded permanently against the revocation.'),
    ('Recorded permanently, and shown to whoever clears it.'),
    ('Release'),
    ('Release, reject, rework or scrap. This is the decision the audit reads.'),
    ('Releasing an order is what makes it work the floor can start.'),
    ('Reorder pt'),
    ('Replay a delivery'),
    ('Requirements run'),
    ('Reserves anything on the order that is not reserved yet, then picks it from the stock that is actually on the shelf. One press does both halves.'),
    ('Restricted'),
    ('Result for the period'),
    ('Result to date'),
    ('Revoke a key'),
    ('Revoking takes effect on the next call. A revoked key is never reinstated.'),
    ('Rotate the secret'),
    ('Route it'),
    ('Route this requisition for approval'),
    ('Rule'),
    ('Safety stock'),
    ('Scrap factor'),
    ('Search Clove ERP…'),
    ('Send back'),
    ('Send it back'),
    ('Send this requisition back'),
    ('Send this requisition for approval'),
    ('Sending one again'),
    ('Service account'),
    ('Short, and the same one the site or department uses where it maps to one.'),
    ('Show account detail'),
    ('Shown to whoever depends on this view.'),
    ('Sign off'),
    ('Sits inside'),
    ('So somebody can find the printer when it jams.'),
    ('Something is found, it is inspected, it is dispositioned, and if it has left the building there is a recall.'),
    ('Stamps the chain the value and the department resolve to, and raises the approval tasks that go with it.'),
    ('Stock audit'),
    ('Stock forecast'),
    ('Stock leaves the store and joins the order''s cost.'),
    ('Stock that leaves your custody without being sold — a keeper, a contract manufacturer.'),
    ('Stock, step by step'),
    ('Storage rules'),
    ('Submit for approval'),
    ('The approval tasks assigned to you or to a role you hold, decided one at a time.'),
    ('The books are kept in this.'),
    ('The carrier''s own service code, from their rate card.'),
    ('The carrier''s proof-of-delivery reference, if they gave one.'),
    ('The code of the job, handler or integration being stopped.'),
    ('The cost centres postings are analysed by, derived from the document''s cost centre, department or site.'),
    ('The customer''s bill, raised from a posted delivery so the quantities are what left.'),
    ('The customer''s code. It is created if it does not exist yet.'),
    ('The domain the DNS records were published for.'),
    ('The domain your documents are sent from.'),
    ('The evidence for what the other side actually did.'),
    ('The exposed view being changed.'),
    ('The exposed view being retired.'),
    ('The governed view outside tools will read.'),
    ('The group it belongs to — pick one already in use or type a new one.'),
    ('The id of that record. Copy it from the record itself.'),
    ('The id of the document being routed. Copy it from the document page.'),
    ('The id of the duplicate. Both ids are shown in the duplicate candidates list.'),
    ('The id of the person, department or role chosen above — copy it from the list on this page.'),
    ('The id of the product or business partner being changed — copy it from Master data.'),
    ('The id of the record everything should point at afterwards.'),
    ('The key the switch was set against.'),
    ('The kind of action this reason belongs to.'),
    ('The language printed documents use, if not the reporting one.'),
    ('The name of the terminal printing. Leave blank for any.'),
    ('The name of whoever signed for the goods.'),
    ('The name shown beside their actions.'),
    ('The number printed on their bill, so it can be matched later.'),
    ('The number shown against the message in the backlog below.'),
    ('The number written on the goods, or the one you are giving them now.'),
    ('The operation that system accepts, as agreed with whoever runs it.'),
    ('The pallet has been moved. Completing the task is what moves the stock.'),
    ('The quantity of the product one run of this bill produces. Usually 1.'),
    ('The reason code to switch.'),
    ('The registered name, if it differs from the one used day to day.'),
    ('The registered name, if it differs from the trading name.'),
    ('The requisition returns to draft, with the reason on the record.'),
    ('The result against the specification, recorded against the batch.'),
    ('The short code of the connected system, as it appears in the backlog.'),
    ('The short code used on documents, for example EA, KG or BOX.'),
    ('The signature or the photograph, attached to the shipment.'),
    ('The words shown wherever this key appears.'),
    ('They sign in with this address.'),
    ('This module has no reports of its own yet.'),
    ('Tick every delivery travelling on this shipment.'),
    ('Tick every role this partner plays.'),
    ('To / as at'),
    ('Total assets'),
    ('Total equity'),
    ('Total expense'),
    ('Total income'),
    ('Total liabilities'),
    ('Turn this quotation into a sales order'),
    ('Turn this requisition into a purchase order'),
    ('Typed in full. It is kept against the release.'),
    ('Unblock a location'),
    ('Unit'),
    ('Usage per day, lead time and reorder point for each product, with days of cover, the date to order by and how much to buy.'),
    ('Use this for results in words. Numbers go in the value box.'),
    ('Used'),
    ('Used / day'),
    ('Variance value'),
    ('Warehouse layout'),
    ('What each made product is made of, version by version.'),
    ('What is being overridden, for example document or journal.'),
    ('What is due to suppliers, gathered into one proposal.'),
    ('What is to be made, how much, and by when.'),
    ('What kind of thing it is. Drives bills of materials and planning.'),
    ('What the amount above is counted in.'),
    ('What the batch should be called from now on.'),
    ('What the count found, or damage: a write-off leaves a movement and a reason.'),
    ('What the counter found in the place. The variance is worked out from it.'),
    ('What the figures above are measured against.'),
    ('What the learner will practise.'),
    ('What the period made and what the company is worth, read from the journals purchases, stock and invoices already posted.'),
    ('What the reading was taken with, if it matters.'),
    ('What the reason means in plain words.'),
    ('What the requester has to change before submitting again.'),
    ('What the rule decides'),
    ('What the run says to buy or make, before anyone has committed to it.'),
    ('What the supplier calls this product on their paperwork.'),
    ('What this organisation analyses its results by, and how much has already been posted to each.'),
    ('What this should be called everywhere in the app.'),
    ('What to order, and by when'),
    ('What was done to put this occurrence right.'),
    ('What was done — a notification, a quarantine, a return.'),
    ('What was measured or checked.'),
    ('What will stop it happening again.'),
    ('What you relied on to decide.'),
    ('Where replies should go, if not the sending address.'),
    ('Who hears about it if nobody acts in time.'),
    ('Who is taking it, at what rate, against which service.'),
    ('Why it happened, not what happened.'),
    ('Why this supplier is qualified.'),
    ('Withdraw a bill of materials'),
    ('Withdraw a storage rule'),
    ('Work out who approves'),
    ('Your own reference for this, such as the bank payment reference.'),
    ('Zones, aisles and bins, what each holds, and the storage rules put-away, replenishment and picking read.'),
    ('actual'),
    ('deliveries'),
    ('held by a check'),
    ('never counted'),
    ('not checked'),
    ('not held'),
    ('planned'),
    ('still open')
  ) as v(text)
on conflict (key, locale) do nothing;

-- The seeding is only worth anything if the words still obey the glossary,
-- and if every key a table names still has its string.
select erp.assert_resource_coverage('en');
select erp.assert_vocabulary_aligned();
