insert into erp_ref.resource (key, locale, value, description)
select erp_ref.ui_key(v), 'en', v, 'Interface wording'
  from (values
  ('A contractor routed to their engaging manager, a new starter under supervision, a project team routed to the project owner.'),
  ('A department'),
  ('A department is one object: it routes an approval and it carries the posting. Bands decide who approves by value; a named assignment overrides that for a person, a role or a whole department.'),
  ('A person'),
  ('A role'),
  ('Add or amend a band'),
  ('Add or amend a department'),
  ('Applies to'),
  ('Approver'),
  ('Approver role code'),
  ('Approvers'),
  ('Approvers act'),
  ('Assign a named approver'),
  ('Assign someone to a department'),
  ('Band'),
  ('Band number'),
  ('Band one takes the request up to its ceiling; higher bands add authority above it.'),
  ('Bands'),
  ('Change request'),
  ('Code'),
  ('Cost centre'),
  ('Default cost centre'),
  ('Department'),
  ('Departments'),
  ('Departments and membership. A person''s primary department at capture is the one that routes their request.'),
  ('Departments, membership, value bands and named approvers — who approves what, and why.'),
  ('Each department is also a reporting dimension value, so a department means the same thing in a stock report and in a profit and loss.'),
  ('End a membership'),
  ('End a named assignment'),
  ('Ends on'),
  ('Escalate after (hours)'),
  ('Escalate to the department manager'),
  ('Fall back to the line manager'),
  ('From'),
  ('Hold the request and raise an exception'),
  ('In parallel'),
  ('In sequence'),
  ('Lower bands'),
  ('Lower bands re-run'),
  ('Manager'),
  ('Membership'),
  ('Mode'),
  ('Name'),
  ('Named approver assignments'),
  ('No'),
  ('No bands are configured. Until one exists, nothing routes by value.'),
  ('No ceiling'),
  ('No departments are configured yet.'),
  ('No named assignments. Everything routes by department band.'),
  ('No — the higher band replaces them'),
  ('Nobody has been assigned to a department yet.'),
  ('Nothing has been routed yet.'),
  ('Object type'),
  ('Order'),
  ('Organisation and approval routing'),
  ('Parallel'),
  ('Parent'),
  ('Payment run'),
  ('People'),
  ('Person'),
  ('Primary'),
  ('Primary department'),
  ('Purchase order'),
  ('Re-approval tolerance (%)'),
  ('Re-run'),
  ('Replaced'),
  ('Replaces the department bands'),
  ('Requisition'),
  ('Resolved by'),
  ('Retire a band'),
  ('Routing decisions taken'),
  ('Sales order'),
  ('Secondary'),
  ('Sequential'),
  ('Sits in front of the department bands'),
  ('Status'),
  ('Subject'),
  ('Subject identifier'),
  ('Supplier invoice'),
  ('The chain as it was resolved, with the rule and version that chose each approver.'),
  ('The primary department in force when a request is raised is the one that routes it.'),
  ('To'),
  ('Up to'),
  ('Vacancy'),
  ('Valid from'),
  ('Valid to'),
  ('Value'),
  ('Value bands'),
  ('Value bands and named assignments. Resolution runs named assignment first, then the department''s bands.'),
  ('Version'),
  ('When'),
  ('When nobody resolves'),
  ('Who would approve this?'),
  ('Yes'),
  ('Yes — lower approvers still act')) as t(v)
on conflict (key, locale) do nothing;