set lock_timeout = '30s';

-- =============================================================================
-- 20261012080000  The contract sweeps are scheduled
-- -----------------------------------------------------------------------------
-- Six sweeps across every organisation have had a handler since September and
-- never a job, so nothing ran them: contracts past their term were never
-- expired, renewals never proposed, a contract's key dates never raised, no
-- invoice schedule generated by itself, no breach of a plan reported, and
-- active users never measured (fleet_poll.sh says so of every client's
-- usage). The control plane held two commercial jobs, the quotes' expiry and
-- the invoice chase, where it should have held eight.
--
-- Each is installed in the platform's own organisation, as the chase was
-- (20260915070000): each handler checks that its session is trusted and
-- walks every organisation or every contract itself, so one job in one
-- organisation serves them all. Daily, in the order one sweep feeds the next
-- (users measured, schedules generated, contracts expired, renewals
-- proposed, key dates raised, breaches reported), each with two days' silence
-- before erp.silent_jobs() says so: a daily job's budget of one day is
-- missed by a minute's lateness. A database with no platform organisation
-- (the demonstration, a client, a build's own) is left as it was, with a
-- notice; a client's own organisations are measured by a client's own job,
-- which is not this migration's.
--
-- An existing job of the same code is updated in place, so the migration can
-- run again, and a job the owner has switched off stays off.
--
-- Run by the scheduler for the first time here, three of the six failed: a
-- sweep that acts in each organisation in turn ended by clearing the job's
-- organisation, so the scheduler could not record the run it was in
-- (CLOVEERP_NO_TENANT_CONTEXT). erp_meta.act_in_tenant() now keeps the
-- organisation it found, when it first sets the person aside, and
-- erp_meta.stop_acting_in_tenant() gives that back instead of none, and
-- changes nothing when nothing acted; a caller that had none still ends with
-- none. erp.report_entitlement_breaches(),
-- which set the organisation itself, acts through the pair.
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- A. Acting in an organisation gives back the one it found
-- ─────────────────────────────────────────────────────────────────────────────

do $anchors$
declare r record; v_src text;
begin
  for r in
    select * from (values
      ('erp_meta.act_in_tenant(uuid)',     '7314cffb3e43566228b75a4bed9b02bd'),
      ('erp_meta.stop_acting_in_tenant()', 'ad92f58c41bd2ed5250d0558b14e055b')
    ) v(sig, anchor)
  loop
    v_src := (select p.prosrc from pg_catalog.pg_proc p where p.oid = r.sig::regprocedure);
    if strpos(v_src, '20261012080000') = 0 and md5(v_src) <> r.anchor then
      raise exception 'CLOVEERP_ANCHOR_MOVED: % is not the body this migration was written against', r.sig
        using hint = 'Write the change against the body the database holds now.';
    end if;
  end loop;
end
$anchors$;

create or replace function erp_meta.act_in_tenant(p_tenant_id uuid)
returns void
language plpgsql
set search_path = ''
as $$
begin
  -- Only a session that may declare a tenant at all. A signed-in caller reaches
  -- this only from inside a security definer routine, which is that session.
  if not erp.session_is_trusted() then
    raise exception 'CLOVEERP_UNTRUSTED_CONTEXT_ASSERTION: role % may not act inside an organisation', current_user
      using errcode = '42501';
  end if;
  -- The person is set aside once; a second call only moves to another
  -- organisation, so a routine that walks several keeps the first identity.
  -- The organisation the call began in is kept with it, so a scheduled job
  -- that walks every organisation ends in its own (20261012080000).
  if coalesce(current_setting('erp.acting_set_aside', true), '') = '' then
    perform set_config('erp.acting_claims', coalesce(current_setting('request.jwt.claims', true), ''), true);
    perform set_config('erp.acting_claim_sub', coalesce(current_setting('request.jwt.claim.sub', true), ''), true);
    perform set_config('erp.acting_prior_tenant', coalesce(current_setting('erp.job_tenant_id', true), ''), true);
    perform set_config('erp.acting_set_aside', 'yes', true);
  end if;
  perform set_config('request.jwt.claims', '', true);
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('erp.job_tenant_id', coalesce(p_tenant_id::text, ''), true);
end;
$$;

create or replace function erp_meta.stop_acting_in_tenant()
returns void
language plpgsql
set search_path = ''
as $$
begin
  -- The organisation the first erp_meta.act_in_tenant() found, or none; a
  -- routine that walked no organisation at all leaves the one it is in
  -- (20261012080000).
  if coalesce(current_setting('erp.acting_set_aside', true), '') <> '' then
    perform set_config('erp.job_tenant_id', coalesce(current_setting('erp.acting_prior_tenant', true), ''), true);
    perform set_config('erp.acting_prior_tenant', '', true);
    perform set_config('request.jwt.claims', coalesce(current_setting('erp.acting_claims', true), ''), true);
    perform set_config('request.jwt.claim.sub', coalesce(current_setting('erp.acting_claim_sub', true), ''), true);
    perform set_config('erp.acting_set_aside', '', true);
    perform set_config('erp.acting_claims', '', true);
    perform set_config('erp.acting_claim_sub', '', true);
  end if;
end;
$$;

comment on function erp_meta.stop_acting_in_tenant() is
  'Ends erp_meta.act_in_tenant(): gives back the organisation the first call found (a scheduled job''s own, or '
  'none) and the signed-in person to the rest of the call; with no call to end, changes nothing (20261012080000).';

-- erp.report_entitlement_breaches() set each organisation itself and ended
-- with none; it acts through the pair now.
do $breaches$
declare
  v_sig text := 'erp.report_entitlement_breaches()';
  v_src text := (select p.prosrc from pg_catalog.pg_proc p where p.oid = 'erp.report_entitlement_breaches()'::regprocedure);
  v_def text;
  v_olds text[] := array[
    $o$    perform set_config('erp.job_tenant_id', r.id::text, true);$o$,
    $o$  perform set_config('erp.job_tenant_id', '', true);
  return v_raised;$o$];
  v_news text[] := array[
    $n$    perform erp_meta.act_in_tenant(r.id);$n$,
    $n$  -- The organisation the job began in, given back (20261012080000).
  perform erp_meta.stop_acting_in_tenant();
  return v_raised;$n$];
begin
  if strpos(v_src, '20261012080000') > 0 then
    raise notice '% already carries 20261012080000', v_sig;
    return;
  end if;
  if md5(v_src) <> '33b442b4621a9a2dbbbf6457d38b726a' then
    raise exception 'CLOVEERP_ANCHOR_MOVED: % is not the body this migration was written against', v_sig
      using hint = 'Write the change against the body the database holds now.';
  end if;
  v_def := pg_catalog.pg_get_functiondef(v_sig::regprocedure);
  for i in 1 .. cardinality(v_olds) loop
    if (length(v_def) - length(replace(v_def, v_olds[i], ''))) / length(v_olds[i]) <> 1 then
      raise exception 'CLOVEERP_ANCHOR_MOVED: % does not hold its anchor % exactly once', v_sig, i
        using hint = 'Write the change against the body the database holds now.';
    end if;
    v_def := replace(v_def, v_olds[i], v_news[i]);
  end loop;
  execute v_def;
end
$breaches$;

-- ─────────────────────────────────────────────────────────────────────────────
-- B. The six jobs, in the platform's own organisation
-- ─────────────────────────────────────────────────────────────────────────────

do $sweeps$
declare
  v_platform uuid;
  s record;
  v_enabled boolean;
  v_missing text;
begin
  select po.tenant_id into v_platform from erp_meta.platform_organisation po;
  if v_platform is null then
    raise notice 'no platform organisation here: the contract sweeps are scheduled where there is one';
    return;
  end if;

  perform set_config('erp.job_tenant_id', v_platform::text, true);
  perform set_config('erp.job_principal_id', '', true);

  for s in
    select * from (values
      ('measure_active_users',        'Measure active users',            'commercial.measure_active_users',        '05:30'::time),
      ('generate_invoice_schedules',  'Generate invoice schedules',      'commercial.generate_invoice_schedules',  '06:00'::time),
      ('expire_contracts',            'Expire contracts past their term', 'commercial.expire_contracts',           '06:10'::time),
      ('propose_renewals',            'Propose renewals',                'commercial.propose_renewals',            '06:20'::time),
      ('raise_contract_key_dates',    'Raise contract key dates',        'commercial.raise_contract_key_dates',    '06:30'::time),
      ('report_entitlement_breaches', 'Report entitlement breaches',     'commercial.report_entitlement_breaches', '06:40'::time)
    ) v(code, name, handler_code, at_time)
  loop
    -- A job already here keeps whether it is switched on.
    select j.is_enabled into v_enabled from erp.job j where j.tenant_id = v_platform and j.code = s.code;
    perform erp.upsert_job(s.code, s.name, s.handler_code, 'daily', null, s.at_time,
                           null, null, 'UTC', '{}'::jsonb, null, 172800, coalesce(v_enabled, true));
  end loop;

  perform set_config('erp.job_tenant_id', '', true);

  select string_agg(h, ', ') into v_missing
    from unnest(array['commercial.measure_active_users', 'commercial.generate_invoice_schedules',
                      'commercial.expire_contracts', 'commercial.propose_renewals',
                      'commercial.raise_contract_key_dates', 'commercial.report_entitlement_breaches']) h
   where not exists (select 1 from erp.job j where j.tenant_id = v_platform and j.handler_code = h);
  if v_missing is not null then
    raise exception 'CLOVEERP_SWEEP_NOT_SCHEDULED: % has no job in the platform organisation', v_missing
      using hint = 'Each sweep needs one job in the platform''s own organisation; erp.upsert_job() was refused for it.';
  end if;
end
$sweeps$;

-- The generators, which are idempotent and run at the end of every migration.

select erp.apply_row_security();
select erp.apply_platform_internal_security();
select erp.apply_append_only_guards();
select erp.apply_attribution_triggers();
select erp.apply_audit_coverage();
select erp.apply_live_config_guards();
select erp.apply_execute_grants();

select erp.assert_isolation();
select erp.assert_public_api_safe();
select erp.assert_no_public_execute();
select erp.assert_no_legacy_refusal_prefix();
select erp.assert_refusals_name_next_action();
select erp.assert_diagnostics_registered();
select erp.assert_ci_coverage();
select erp.assert_suite_verdicts_strict();
select erp.assert_enforcement_gates_are_read();
select erp.assert_resource_coverage('en');
select erp.assert_resource_coverage_de();
select erp.assert_personal_data_register_sound();
